export type ArchiveNodeType = 'character' | 'event' | 'rule' | 'truth' | 'faction';
export type FlowCardType = 'character' | 'event' | 'mechanic' | 'result' | 'transition';

export type ArchiveNode = {
  id: string;
  type: ArchiveNodeType;
  title: string;
  subtitle: string;
  summary: string;
  sections: Array<{ label: string; value: string }>;
  tags: string[];
  timeline: string[];
};

export type ArchiveEdge = {
  source: string;
  target: string;
  label: string;
};

export type TimelineEvent = {
  id: string;
  label: string;
  phase: string;
  detail: string;
};

export type FlowCard = {
  id: string;
  title: string;
  subtitle: string;
  summary: string;
  type: FlowCardType;
};

export type DoomFlowLane = {
  id: string;
  title: string;
  cardIds: string[];
};

export type DoomPhase = {
  id: string;
  rangeLabel: string;
  title: string;
  kicker: string;
  keywords: string[];
  entry: string;
  lanes: DoomFlowLane[];
};

export type RiverBand = 'prelude' | 'mechanic' | 'core' | 'outcome' | 'transition';

export type RiverStage = {
  id: string;
  rangeLabel: string;
  title: string;
  kicker: string;
  keywords: string[];
  coreCharacters: string[];
  coreEvents: string[];
  coreMechanics: string[];
  stageResult: string;
};

export type RiverNode = {
  id: string;
  cardId: string;
  stageId: string;
  band: RiverBand;
  x: number;
  y: number;
  size: 'sm' | 'md' | 'lg';
  importance: 1 | 2 | 3;
};

export type RiverLink = {
  source: string;
  target: string;
  strength: 'soft' | 'medium' | 'strong';
};

export type MuseumHall = {
  id: string;
  title: string;
  label: string;
  subtitle: string;
  description: string;
  accent: 'primary' | 'secondary' | 'muted';
};

export const characterEchoNames: Record<string, string> = {
  qixia: '生生不息',
  linqin: '激发',
  qiaojiajin: '破万法',
  hanyimo: '招灾',
  xuliunian: '化形',
  yunyao: '强运',
  zhangshan: '天行健',
  jiangruoxue: '因果',
  zhoumo: '传音',
};

export const archiveNodes: ArchiveNode[] = [
  {
    id: 'qixia',
    type: 'character',
    title: '齐夏',
    subtitle: '欺诈与推演',
    summary: '他把混乱解释为规则，再把规则反过来变成自己的工具，是整张网的核心启动力。',
    sections: [
      { label: '人物定位', value: '认知中心、规则拆解者、长期布局者。' },
      { label: '初始状态', value: '失忆、冷静、先观察再下注，对任何叙述都天然保持怀疑。' },
      { label: '心理变化', value: '从只想带着余念安离开，到逐渐接受自己必须把整套终焉结构拆开。' },
      { label: '关键关系', value: '与林檎形成高压共谋，与乔家劲形成稳定互补，与陈俊南形成长期默契。' },
      { label: '终局意义', value: '他的存在让“活下去”升级成了“重写终焉之地”。' },
    ],
    tags: ['主控节点', '规则拆解', '认知中心'],
    timeline: ['opening-bet', 'false-alliance', 'echo-awakening', 'paradise-mouth', 'final-gate'],
  },
  {
    id: 'linqin',
    type: 'character',
    title: '林檎',
    subtitle: '锋利的共谋者',
    summary: '她不是跟随者，而是少数能迅速理解齐夏并主动加码的人。',
    sections: [
      { label: '人物定位', value: '识别者、共谋者、判断力放大器。' },
      { label: '初始状态', value: '对任何新秩序都先做识别与试探，不轻易交出真实立场。' },
      { label: '心理变化', value: '从把齐夏视为高价值样本，到把自己主动押进更深层的合作里。' },
      { label: '关键关系', value: '与齐夏是双向押注，与极道脉络存在短暂咬合。' },
      { label: '终局意义', value: '她让主角团不只是追随齐夏，而是真正形成高压共谋。' },
    ],
    tags: ['共谋', '识别力', '反压迫'],
    timeline: ['opening-bet', 'false-alliance', 'echo-awakening', 'paradise-mouth'],
  },
  {
    id: 'qiaojiajin',
    type: 'character',
    title: '乔家劲',
    subtitle: '直觉破局者',
    summary: '他的直觉和行动让主角团不只是会想，也真的能硬顶着局面往前走。',
    sections: [
      { label: '人物定位', value: '执行锚点、保护者、硬解型角色。' },
      { label: '初始状态', value: '先行动、后解释，对规则的直觉往往先于完整论证。' },
      { label: '心理变化', value: '从单纯托底到主动承担“必须有人上前”的结构责任。' },
      { label: '关键关系', value: '与齐夏形成认知-执行互补，与楚天秋旧交情复杂重排。' },
      { label: '终局意义', value: '他是整张网络里最稳定的执行锚点之一。' },
    ],
    tags: ['执行力', '直觉', '硬碰硬'],
    timeline: ['opening-bet', 'false-alliance', 'paradise-mouth', 'dragon-collapse'],
  },
  {
    id: 'chenjunnan',
    type: 'character',
    title: '陈俊南',
    subtitle: '不可靠的可靠者',
    summary: '他总像游离在边缘，却不断把人物与事件重新缠在一起。',
    sections: [
      { label: '人物定位', value: '串联者、气氛缓冲带、长期陪伴型节点。' },
      { label: '初始状态', value: '嘴贫、松弛、带着明显的游离感进入主线。' },
      { label: '心理变化', value: '从看起来最像局外人，到不断在关键点承担最脏最重的部分。' },
      { label: '关键关系', value: '与齐夏形成长期默契，与猫队和天堂口都能保留沟通缝隙。' },
      { label: '终局意义', value: '他让整张大网拥有更复杂的人情牵连。' },
    ],
    tags: ['混沌感', '人情链接', '游离态'],
    timeline: ['opening-bet', 'false-alliance', 'paradise-mouth', 'final-gate'],
  },
  {
    id: 'tiantian',
    type: 'character',
    title: '甜甜',
    subtitle: '脆弱感的锚点',
    summary: '她让每一个策略选择都带上切身痛感，把抽象规则重新拉回人。',
    sections: [
      { label: '人物定位', value: '道德摩擦承载者、情绪锚点、弱势视角入口。' },
      { label: '初始状态', value: '脆弱、恐惧、被保护，但并非毫无选择。' },
      { label: '心理变化', value: '从只能承受代价，到逐渐在被保护中产生自己的坚持。' },
      { label: '关键关系', value: '与齐夏形成典型“保护如何制造代价”的关系。' },
      { label: '终局意义', value: '她让合作不只是策略，也始终带着道德摩擦。' },
    ],
    tags: ['脆弱感', '情绪锚点', '求生反应'],
    timeline: ['opening-bet', 'false-alliance', 'echo-awakening'],
  },
  {
    id: 'hanyimo',
    type: 'character',
    title: '韩一墨',
    subtitle: '局中噪声',
    summary: '他代表了终焉之地里最直接的恐惧、冲动与失衡。',
    sections: [
      { label: '人物定位', value: '风险放大器、不稳定因素、普通人阴影面。' },
      { label: '初始状态', value: '先被恐惧牵着走，再把恐惧扩散给整个队伍。' },
      { label: '心理变化', value: '不是成长线，而是不断证明失控会怎样毁掉合作。' },
      { label: '关键关系', value: '与齐夏构成典型的压制与止损关系。' },
      { label: '终局意义', value: '他的存在让主角团不可能平稳合作。' },
    ],
    tags: ['冲动', '失衡', '风险触发'],
    timeline: ['opening-bet'],
  },
  {
    id: 'xuliunian',
    type: 'character',
    title: '许流年',
    subtitle: '押送与见证',
    summary: '她常出现在更深层的真相与轮回叙事里，是终焉结构的重要见证者之一。',
    sections: [
      { label: '人物定位', value: '见证者、押送者、深层信息接口。' },
      { label: '初始状态', value: '比大多数人更早知道终焉不只是游戏。' },
      { label: '心理变化', value: '在知情、隐瞒与试探中维持复杂平衡。' },
      { label: '关键关系', value: '与齐夏共享更深的轮回信息，与终焉之地形成错位连接。' },
      { label: '终局意义', value: '她把人物线进一步推向世界真相。' },
    ],
    tags: ['见证者', '轮回深层', '真相接口'],
    timeline: ['echo-awakening', 'paradise-mouth', 'final-gate'],
  },
  {
    id: 'chutianqiu',
    type: 'character',
    title: '楚天秋',
    subtitle: '天堂口的良人王',
    summary: '他代表了另一种组织化生存路径，也让“同伴”与“利用”之间的边界持续晃动。',
    sections: [
      { label: '人物定位', value: '天堂口领袖、秩序型组织者、主线对照角色。' },
      { label: '初始状态', value: '把生存问题率先转成管理和秩序问题。' },
      { label: '心理变化', value: '从建立共同体，到不断为共同体支付越来越沉重的代价。' },
      { label: '关键关系', value: '与文巧云是前史核心关系，与齐夏形成高位对照。' },
      { label: '终局意义', value: '他让齐夏的路线不再是终焉之地唯一解法。' },
    ],
    tags: ['天堂口', '组织者', '对照路线'],
    timeline: ['paradise-mouth', 'dragon-collapse', 'final-gate'],
  },
  {
    id: 'yanzhichun',
    type: 'character',
    title: '燕知春',
    subtitle: '极道引线',
    summary: '她把人物行动从单纯求生推进到组织性反抗，是极道脉络的重要起点。',
    sections: [
      { label: '人物定位', value: '极道王、组织动员者、反抗线中心。' },
      { label: '初始状态', value: '并非天生领袖，而是在说谎与行动中逐渐站到最前面。' },
      { label: '心理变化', value: '从愿景驱动到策略驱动，再到承受组织口碑震荡。' },
      { label: '关键关系', value: '与白羊是塑造与被塑造关系，与江若雪形成王与军师结构。' },
      { label: '终局意义', value: '她使终焉之地的对抗线更立体。' },
    ],
    tags: ['极道', '组织脉络', '反抗线'],
    timeline: ['paradise-mouth', 'dragon-collapse', 'final-gate'],
  },
  {
    id: 'wenqiaoyun',
    type: 'character',
    title: '文巧云',
    subtitle: '早期反抗的残响',
    summary: '她是更早期反抗天龙的重要人物，其经历反向照亮了后来的很多布局。',
    sections: [
      { label: '人物定位', value: '前史节点、早期反抗者、天堂口前身核心。' },
      { label: '初始状态', value: '早于主线人物开始反抗终焉秩序。' },
      { label: '心理变化', value: '在爱、秩序与反抗之间不断被撕扯。' },
      { label: '关键关系', value: '与楚天秋是共创型伴侣关系，与青龙形成压制与收编关系。' },
      { label: '终局意义', value: '她让终焉之地的历史纵深变得真实。' },
    ],
    tags: ['早期反抗', '历史层', '遗产'],
    timeline: ['paradise-mouth', 'dragon-collapse'],
  },
  {
    id: 'yunyao',
    type: 'character',
    title: '云瑶',
    subtitle: '强运的变数',
    summary: '她作为天堂口的重要人物之一，为组织脉络加入更强的偶然性与失控感。',
    sections: [
      { label: '人物定位', value: '强运变量、组织情感缓冲层。' },
      { label: '初始状态', value: '在天堂口内部承担连接与缓冲。' },
      { label: '心理变化', value: '随着组织逻辑变硬，她逐渐从内部失去认同。' },
      { label: '关键关系', value: '与楚天秋是高位搭档失衡关系，与张山形成同阵营默契。' },
      { label: '终局意义', value: '她强化了天堂口与主角团之间的差异。' },
    ],
    tags: ['天堂口', '强运', '变量'],
    timeline: ['paradise-mouth', 'dragon-collapse'],
  },
  {
    id: 'zhangshan',
    type: 'character',
    title: '张山',
    subtitle: '后来加入的变量',
    summary: '他的出现连接了后期布局与组织重组，是中后段脉络里的关键变量人物。',
    sections: [
      { label: '人物定位', value: '中后段变量、战力补位、结构推进器。' },
      { label: '初始状态', value: '不是最早的核心人物，却在中后段不断提高存在感。' },
      { label: '心理变化', value: '从加入者变成真正影响结构走向的参与者。' },
      { label: '关键关系', value: '与乔家劲共同构成硬推进节点，与天堂口路径交叉。' },
      { label: '终局意义', value: '他补强了中后段群像的复杂度。' },
    ],
    tags: ['变量', '中后段', '重组'],
    timeline: ['paradise-mouth', 'dragon-collapse', 'final-gate'],
  },
  {
    id: 'yunianan',
    type: 'character',
    title: '余念安',
    subtitle: '现实锚点与执念容器',
    summary: '她既是齐夏不断回望的现实锚点，也是全书争议最大的“她究竟如何存在”之谜。',
    sections: [
      { label: '人物定位', value: '现实锚点、情感母题、存在争议核心。' },
      { label: '初始状态', value: '最初代表离开终焉的方向，后期逐渐变成世界解释难题。' },
      { label: '心理变化', value: '她不是传统人物弧线，而是齐夏心理与世界真相的交叉接口。' },
      { label: '关键关系', value: '与齐夏是执念与救赎关系，也与“现实是否可信”强绑定。' },
      { label: '终局意义', value: '她把私人情感线直接拖进了世界结构层。' },
    ],
    tags: ['现实锚点', '执念', '存在争议'],
    timeline: ['prelude-memory', 'opening-bet', 'final-gate'],
  },
  {
    id: 'jiangruoxue',
    type: 'character',
    title: '江若雪',
    subtitle: '极道军师',
    summary: '她让极道不只是高热口号，而是拥有真正的谋划、串联和执行逻辑。',
    sections: [
      { label: '人物定位', value: '军师、连接器、因果型能力节点。' },
      { label: '初始状态', value: '更偏谋划与推演，在阵营内承担翻译意志的功能。' },
      { label: '心理变化', value: '从把人组织起来，到承担组织越来越复杂的因果。' },
      { label: '关键关系', value: '与燕知春形成王与军师互补，与白羊存在间接合作。' },
      { label: '终局意义', value: '她让极道的组织结构比单一领袖叙事更完整。' },
    ],
    tags: ['极道', '军师', '因果'],
    timeline: ['paradise-mouth', 'dragon-collapse'],
  },
  {
    id: 'zhoumo',
    type: 'character',
    title: '周末',
    subtitle: '极道传音节点',
    summary: '她在群像里像一条细线，把分散的信息和情绪往同一组织方向拢。',
    sections: [
      { label: '人物定位', value: '传音节点、信息串联者。' },
      { label: '初始状态', value: '存在感不最高，但负责把阵营内部的线继续连住。' },
      { label: '心理变化', value: '她的成长更多体现为“被卷入结构之后是否继续站住”。' },
      { label: '关键关系', value: '与极道是串联型服务关系。' },
      { label: '终局意义', value: '她补足了极道不止靠核心主角运转这一层。' },
    ],
    tags: ['极道', '传音', '串联'],
    timeline: ['paradise-mouth'],
  },
  {
    id: 'lishangwu',
    type: 'character',
    title: '李尚武',
    subtitle: '普通人样本',
    summary: '他代表了终焉里最常见、也最容易被忽略的那类人：想活、怕死、会犹豫，但并不天然失格。',
    sections: [
      { label: '人物定位', value: '普通人样本、开局人群中的现实面。' },
      { label: '初始状态', value: '更偏现实感，面对高压时先考虑保命。' },
      { label: '心理变化', value: '从被规则推着走，到逐渐学会在夹缝里站稳。' },
      { label: '关键关系', value: '与韩一墨、第一间房的初始人群形成对照。' },
      { label: '终局意义', value: '他让人物馆不只剩核心主角，也能看到普通人的被迫成长。' },
    ],
    tags: ['普通人', '开局样本', '生存感'],
    timeline: ['opening-bet', 'false-alliance'],
  },
  {
    id: 'xiaoran',
    type: 'character',
    title: '萧冉',
    subtitle: '开局异常点',
    summary: '她更像是被放进起点结构里的异常变量，体量不大，但对开局结构有明显扰动。',
    sections: [
      { label: '人物定位', value: '开局异常投放点、事件接口人物。' },
      { label: '初始状态', value: '在第一间房中承担一种容易被牺牲或被重新定义的位置。' },
      { label: '心理变化', value: '更适合作为“被安排的人”来理解，而不是单独英雄线。' },
      { label: '关键关系', value: '与第一间房、说谎筛人、初始站位相关。' },
      { label: '终局意义', value: '她帮助我们看见开局并不是自然随机，而是结构安排。' },
    ],
    tags: ['开局', '异常点', '初始结构'],
    timeline: ['opening-bet'],
  },
  {
    id: 'lishangling',
    type: 'character',
    title: '李香玲',
    subtitle: '试探型节点',
    summary: '她更偏向在局内做试探和信息传递，属于人物馆需要补齐的细颗粒度连接点。',
    sections: [
      { label: '人物定位', value: '试探者、局内连接点、弱关系观察者。' },
      { label: '初始状态', value: '更早意识到规则压力的人之一。' },
      { label: '心理变化', value: '从旁观试探到参与局势重排。' },
      { label: '关键关系', value: '与主角团早期关系网、信息链和临时协作相关。' },
      { label: '终局意义', value: '补足“普通却有存在感”的人物层。' },
    ],
    tags: ['试探', '信息链', '补充人物'],
    timeline: ['opening-bet', 'false-alliance'],
  },
  {
    id: 'sushan',
    type: 'character',
    title: '苏闪',
    subtitle: '高智协作样本',
    summary: '她适合被写成高智而克制的协作样本，补足人物馆中的女性判断力层。',
    sections: [
      { label: '人物定位', value: '高智协作节点、女性判断型角色。' },
      { label: '初始状态', value: '先识别环境再决定站位。' },
      { label: '心理变化', value: '从独立判断走向更深的群体协作。' },
      { label: '关键关系', value: '与主角团、天堂口和极道线都可挂接。' },
      { label: '终局意义', value: '补齐“冷静、能看懂局势”的人物密度。' },
    ],
    tags: ['高智', '协作', '补充人物'],
    timeline: ['false-alliance', 'paradise-mouth'],
  },
  {
    id: 'qindingdong',
    type: 'character',
    title: '秦丁冬',
    subtitle: '轻社交补位',
    summary: '她更适合作为关系馆和人物馆之间的轻社交补位，负责拉出日常感和局内互动。',
    sections: [
      { label: '人物定位', value: '轻社交节点、群体气氛补位。' },
      { label: '初始状态', value: '更容易被卷入局势边缘。' },
      { label: '心理变化', value: '从边缘参与者逐渐成为可辨认的关系节点。' },
      { label: '关键关系', value: '与主角团和阵营过渡线都有交集。' },
      { label: '终局意义', value: '补齐群像的温度层。' },
    ],
    tags: ['轻社交', '边缘人物', '温度层'],
    timeline: ['false-alliance', 'paradise-mouth'],
  },
  {
    id: 'qianwu',
    type: 'character',
    title: '钱五',
    subtitle: '猫队协作位',
    summary: '钱五适合作为猫队与任务联盟线里的执行节点，帮助补足猫队群像。',
    sections: [
      { label: '人物定位', value: '猫队协作位、任务节点。' },
      { label: '初始状态', value: '更偏任务导向。' },
      { label: '心理变化', value: '随着局势推进逐渐被卷入更大的结构对抗。' },
      { label: '关键关系', value: '与猫队、陈俊南以及临时共谋线相关。' },
      { label: '终局意义', value: '补齐任务联盟的可见人物。' },
    ],
    tags: ['猫队', '任务', '协作'],
    timeline: ['dragon-collapse'],
  },
  {
    id: 'qianduoduo',
    type: 'character',
    title: '钱多多',
    subtitle: '猫队补位',
    summary: '钱多多作为补位人物，帮助猫队从名词变成可阅读的人物群像。',
    sections: [
      { label: '人物定位', value: '猫队补位、任务型边角节点。' },
      { label: '初始状态', value: '更偏服从任务与快速反应。' },
      { label: '心理变化', value: '从执行者变成会被关系牵引的参与者。' },
      { label: '关键关系', value: '与猫队、陈俊南和局部协作事件相关。' },
      { label: '终局意义', value: '补足猫队的人物厚度。' },
    ],
    tags: ['猫队', '补位', '执行'],
    timeline: ['dragon-collapse'],
  },
  {
    id: 'jinyuanxun',
    type: 'character',
    title: '金元勋',
    subtitle: '信息中介',
    summary: '他更多以中介和信息链节点的姿态出现，负责让阵营之间避免完全断联。',
    sections: [
      { label: '人物定位', value: '信息中介、阵营消息链节点。' },
      { label: '初始状态', value: '更偏功能型角色，不一定总站在第一线。' },
      { label: '心理变化', value: '在信息传递、转述与风险控制之间维持平衡。' },
      { label: '关键关系', value: '与楚天秋、齐夏之间存在避免正面冲突的信息链。' },
      { label: '终局意义', value: '他补齐了“不是所有关键连接都必须正面对话”的结构感。' },
    ],
    tags: ['信息链', '中介', '转述'],
    timeline: ['paradise-mouth', 'dragon-collapse'],
  },
  {
    id: 'luxiaoxiao',
    type: 'character',
    title: '陆潇潇',
    subtitle: '极道执行端',
    summary: '她更像极道里处理脏活和硬活的功能位，存在感未必最高，但能让组织真正转起来。',
    sections: [
      { label: '人物定位', value: '脏活执行端、局势搅动位。' },
      { label: '初始状态', value: '承担的是组织行动而非情绪中心。' },
      { label: '心理变化', value: '从执行任务到逐渐成为组织结构的一部分。' },
      { label: '关键关系', value: '与燕知春、江若雪共同构成极道的行动侧。' },
      { label: '终局意义', value: '她补足极道不是只有领袖和军师，而是还有执行层。' },
    ],
    tags: ['极道', '执行端', '行动侧'],
    timeline: ['paradise-mouth', 'dragon-collapse'],
  },
  {
    id: 'tongchan',
    type: 'character',
    title: '童婵',
    subtitle: '信仰追随者',
    summary: '她更像极道群像里的信念承接者，负责把领袖神话落回具体人身上。',
    sections: [
      { label: '人物定位', value: '信仰型追随者、群像补位。' },
      { label: '初始状态', value: '更依赖组织信念来确认自己的位置。' },
      { label: '心理变化', value: '从跟随到参与，再到理解组织为什么需要这种相信。' },
      { label: '关键关系', value: '与燕知春、江若雪和极道整体绑定。' },
      { label: '终局意义', value: '她让极道的“信念型绑定”具备具体人物载体。' },
    ],
    tags: ['极道', '信仰', '追随'],
    timeline: ['paradise-mouth', 'dragon-collapse'],
  },
  {
    id: 'guyu',
    type: 'character',
    title: '顾禹',
    subtitle: '边缘锋刃',
    summary: '他适合放进极道和猫队一类的高风险协作区域，承担的是锐边和边缘功能。',
    sections: [
      { label: '人物定位', value: '边缘锋刃、高风险功能位。' },
      { label: '初始状态', value: '不是最大声的那个，但经常承担最危险的功能。' },
      { label: '心理变化', value: '更像是在战局里被迫磨出的角色，而不是先天型领袖。' },
      { label: '关键关系', value: '与极道执行层、临时任务联盟有交集。' },
      { label: '终局意义', value: '他补充了群像里“锋刃型边缘人物”的空间。' },
    ],
    tags: ['高风险', '边缘锋刃', '执行'],
    timeline: ['paradise-mouth', 'dragon-collapse'],
  },
  {
    id: 'shuhua',
    type: 'character',
    title: '舒画',
    subtitle: '白羊系节点',
    summary: '她是白羊路径上很典型的“被保护、被塑形、又被卷入制度”的人物样本。',
    sections: [
      { label: '人物定位', value: '白羊系关系节点、依附与服从样本。' },
      { label: '初始状态', value: '更容易被强势人格和承诺吸引。' },
      { label: '心理变化', value: '从私人依恋滑向制度化执行。' },
      { label: '关键关系', value: '与白羊、极乐钱庄、白羊体系网络相关。' },
      { label: '终局意义', value: '她让“保护、利用、压制”三位一体更容易被看见。' },
    ],
    tags: ['白羊系', '依附', '制度化'],
    timeline: ['paradise-mouth', 'dragon-collapse'],
  },
  {
    id: 'baiyang',
    type: 'character',
    title: '白羊',
    subtitle: '塑造者',
    summary: '白羊是必须单列的人物，因为很多人物、很多回响和很多组织关系最后都能回收到他这条线。',
    sections: [
      { label: '人物定位', value: '布局者、白羊体系核心、学生链源头。' },
      { label: '初始状态', value: '长期布局、会筛人、会塑人。' },
      { label: '心理变化', value: '更像把世界当成一盘可以继续扩大的局。' },
      { label: '关键关系', value: '与燕知春、舒画、江若雪及多条收益模型相关。' },
      { label: '终局意义', value: '他是角色、事件、关系和世界观的共同汇流点。' },
    ],
    tags: ['白羊', '布局', '塑造'],
    timeline: ['prelude-memory', 'opening-bet', 'final-gate'],
  },
  {
    id: 'qinglong',
    type: 'character',
    title: '青龙',
    subtitle: '上位秩序执行体',
    summary: '青龙不是普通反派，而是上位秩序的具体执行面，带着很强的压迫与制度感。',
    sections: [
      { label: '人物定位', value: '上位秩序执行核心、强敌样本。' },
      { label: '初始状态', value: '一开始就是压场型存在。' },
      { label: '心理变化', value: '更像与世界结构共生的执行者，而不是单纯情绪化反派。' },
      { label: '关键关系', value: '与天龙、齐夏、文巧云、楚天秋都构成高位拉扯。' },
      { label: '终局意义', value: '他补足了顶层秩序的人物化表达。' },
    ],
    tags: ['青龙', '秩序', '压迫感'],
    timeline: ['dragon-collapse', 'final-gate'],
  },
  {
    id: 'tianlong',
    type: 'character',
    title: '天龙',
    subtitle: '顶层定义者',
    summary: '他代表的是想把世界收束成唯一答案的顶层控制欲，也是终局真相层最重要的人物之一。',
    sections: [
      { label: '人物定位', value: '终局秩序定义者、真相层核心人物。' },
      { label: '初始状态', value: '站在制度顶端，以控制和定义世界为核心。' },
      { label: '心理变化', value: '越到后期越显出投机、偏执和对唯一答案的执着。' },
      { label: '关键关系', value: '与青龙构成双核秩序，与参与者形成创造者幻想式控制。' },
      { label: '终局意义', value: '他是“旧世界如何被篡改”的关键入口。' },
    ],
    tags: ['天龙', '顶层', '控制欲'],
    timeline: ['dragon-collapse', 'final-gate'],
  },
  {
    id: 'xuanwu',
    type: 'character',
    title: '玄武',
    subtitle: '结构压迫执行体',
    summary: '玄武更像高位秩序中的结构执行面，负责把压迫做成稳定运行的程序。',
    sections: [
      { label: '人物定位', value: '结构压迫执行体、高位秩序节点。' },
      { label: '初始状态', value: '从一开始就站在更高层权限边上。' },
      { label: '心理变化', value: '更像权力结构的延伸，而非独立成长线。' },
      { label: '关键关系', value: '与天龙、青龙、白羊等顶层结构相连。' },
      { label: '终局意义', value: '补齐高位秩序的人物层厚度。' },
    ],
    tags: ['玄武', '高位秩序', '执行'],
    timeline: ['dragon-collapse', 'final-gate'],
  },
  {
    id: 'zhuque',
    type: 'character',
    title: '朱雀',
    subtitle: '被猎杀节点',
    summary: '朱雀更多体现高位秩序里的脆弱面和被追猎面，让顶层并非绝对稳固。',
    sections: [
      { label: '人物定位', value: '高位秩序节点、被追猎对象。' },
      { label: '初始状态', value: '处于制度和猎杀共同作用的高位边缘。' },
      { label: '心理变化', value: '更像顶层结构中的脆弱裂点。' },
      { label: '关键关系', value: '与青龙、天龙及终局追猎线相连。' },
      { label: '终局意义', value: '帮助观众看见顶层也会失稳。' },
    ],
    tags: ['朱雀', '高位秩序', '裂点'],
    timeline: ['dragon-collapse', 'final-gate'],
  },
  {
    id: 'baihu',
    type: 'character',
    title: '白虎',
    subtitle: '白虎位',
    summary: '白虎更适合作为高位秩序与极道、拆钟争议之间的冲突节点。',
    sections: [
      { label: '人物定位', value: '白虎位、争议冲突节点。' },
      { label: '初始状态', value: '更偏对抗和界定边界。' },
      { label: '心理变化', value: '体现结构压迫如何在高位人物上留下痕迹。' },
      { label: '关键关系', value: '与极道线、天级秩序和争议节点相连。' },
      { label: '终局意义', value: '补齐生肖顶层的人物面。' },
    ],
    tags: ['白虎', '高位秩序', '冲突'],
    timeline: ['dragon-collapse', 'final-gate'],
  },
  {
    id: 'tianniu',
    type: 'character',
    title: '天牛',
    subtitle: '天级陨落样本',
    summary: '天牛更像天级体系里能够帮助解释层级崩坏的样本人物。',
    sections: [
      { label: '人物定位', value: '天级样本、层级说明节点。' },
      { label: '初始状态', value: '处于高位秩序中但并不总是中心位。' },
      { label: '心理变化', value: '更适合承接制度性力量与坠落感。' },
      { label: '关键关系', value: '与天龙、青龙和生肖层统治相关。' },
      { label: '终局意义', value: '补齐天级系统的样本密度。' },
    ],
    tags: ['天牛', '天级', '样本'],
    timeline: ['dragon-collapse', 'final-gate'],
  },
  {
    id: 'renyang',
    type: 'character',
    title: '人羊',
    subtitle: '开局规训者',
    summary: '人羊承担了开局说谎筛人的规训功能，是第一间房里最早把规则压到人物身上的节点。',
    sections: [
      { label: '人物定位', value: '开局规训者、第一间房主持节点。' },
      { label: '初始状态', value: '直接把陌生人拖进身份筛选和信任压力中。' },
      { label: '心理变化', value: '更适合看成规则化执行面，而不是独立情绪角色。' },
      { label: '关键关系', value: '与第一间房、说谎者局、开局人群绑定。' },
      { label: '终局意义', value: '他是人物关系第一次被规则改写的起点。' },
    ],
    tags: ['开局', '规训', '第一间房'],
    timeline: ['opening-bet'],
  },
  {
    id: 'renshe',
    type: 'character',
    title: '人蛇',
    subtitle: '问答压迫体',
    summary: '人蛇将问答与身份判断压到同一层，让规则压力继续升级。',
    sections: [
      { label: '人物定位', value: '问答压迫体、规则升级节点。' },
      { label: '初始状态', value: '以问答、少数与多数、语义缝隙制造压力。' },
      { label: '心理变化', value: '更像关卡功能位，不承担传统人物弧线。' },
      { label: '关键关系', value: '与规则博弈、队伍分层和认知升级相关。' },
      { label: '终局意义', value: '它把“会不会回答”变成比“会不会打”更狠的问题。' },
    ],
    tags: ['问答', '规则升级', '高压'],
    timeline: ['echo-awakening'],
  },
  {
    id: 'dishe',
    type: 'character',
    title: '地蛇',
    subtitle: '密闭高压节点',
    summary: '地蛇是把少数与多数、表情与信息、密闭空间压力压到极限的节点人物。',
    sections: [
      { label: '人物定位', value: '密闭高压节点、语言战场。' },
      { label: '初始状态', value: '通过问答和空间控制制造局势失衡。' },
      { label: '心理变化', value: '更像规则机器的具象，而非独立主角。' },
      { label: '关键关系', value: '与地蛇问答局、信息差和群体恐慌相关。' },
      { label: '终局意义', value: '是事件馆里最适合展示规则如何压迫人物的标本。' },
    ],
    tags: ['地蛇', '高压', '密闭空间'],
    timeline: ['echo-awakening'],
  },
  {
    id: 'diji',
    type: 'character',
    title: '地鸡',
    subtitle: '争斗型结构人物',
    summary: '地鸡作为中段结构人物，更适合承接争斗、压迫和局内冲突的节奏。',
    sections: [
      { label: '人物定位', value: '争斗型结构人物。' },
      { label: '初始状态', value: '更像关卡秩序的一部分。' },
      { label: '心理变化', value: '对应中段房间局和冲突升级。' },
      { label: '关键关系', value: '与中段规则局、参与者对抗相关。' },
      { label: '终局意义', value: '补齐生肖层的中段人物。' },
    ],
    tags: ['地鸡', '争斗', '结构人物'],
    timeline: ['echo-awakening', 'dragon-collapse'],
  },
  {
    id: 'digou',
    type: 'character',
    title: '地狗',
    subtitle: '秩序补位',
    summary: '地狗更偏房间秩序与规则执行的补位人物，用来补足规则制造关系的结构面。',
    sections: [
      { label: '人物定位', value: '房间秩序型节点。' },
      { label: '初始状态', value: '偏执行与控制。' },
      { label: '心理变化', value: '可作为规则如何制造关系的样本。' },
      { label: '关键关系', value: '与房间规则、密闭秩序和上位管理相关。' },
      { label: '终局意义', value: '补齐地级人物的结构感。' },
    ],
    tags: ['地狗', '秩序', '规则'],
    timeline: ['echo-awakening', 'dragon-collapse'],
  },
  {
    id: 'dimap',
    type: 'character',
    title: '地马',
    subtitle: '过渡结构位',
    summary: '地马更适合作为天堂口前史和文巧云影响线上的结构人物。',
    sections: [
      { label: '人物定位', value: '过渡结构位、前史节点。' },
      { label: '初始状态', value: '处于组织与个人之间的过渡位。' },
      { label: '心理变化', value: '体现从局部秩序滑向组织秩序的过渡。' },
      { label: '关键关系', value: '与天堂口前史、文巧云路径相关。' },
      { label: '终局意义', value: '补齐地级结构人物。' },
    ],
    tags: ['地马', '过渡', '前史'],
    timeline: ['paradise-mouth', 'dragon-collapse'],
  },
  {
    id: 'renzhu',
    type: 'character',
    title: '人猪',
    subtitle: '概率赌命节点',
    summary: '人猪把概率、侥幸和判断错位压缩到最早期的赌命局里。',
    sections: [
      { label: '人物定位', value: '概率赌命节点、早期训练场。' },
      { label: '初始状态', value: '在开局阶段把胜率误判和恐惧压力绑定。' },
      { label: '心理变化', value: '更偏规则样本位，不是完整成长角色。' },
      { label: '关键关系', value: '与早期核心人物、赌命局和概率判断相关。' },
      { label: '终局意义', value: '帮助终焉的“算不算得过”主题落地。' },
    ],
    tags: ['人猪', '概率', '赌命'],
    timeline: ['opening-bet'],
  },
  {
    id: 'first-room',
    type: 'event',
    title: '第一间房试炼',
    subtitle: '共犯结构的起点',
    summary: '第一间房不是单纯的开场事件，而是整本书人物关系第一次被强行改写的起点。',
    sections: [
      { label: '前因', value: '陌生人被同时投入规则封闭的极端空间。' },
      { label: '规则', value: '说谎、站位、身份筛选同时发生，信任被改造成风险管理。' },
      { label: '后果', value: '信任第一次从道德问题变成生存手段。' },
      { label: '意义', value: '几乎所有后续人物关系都能追溯到这里的第一次站位。' },
    ],
    tags: ['起点事件', '生存博弈', '关系改写'],
    timeline: ['opening-bet'],
  },
  {
    id: 'human-pig',
    type: 'event',
    title: '人猪赌命局',
    subtitle: '概率与侥幸的早期训练场',
    summary: '它让人物第一次明确意识到，在终焉里“算不算得过”比“愿不愿意赌”更重要。',
    sections: [
      { label: '规则', value: '以概率、判断与冒险作为主要施压方式，把群体心理直接推上台面。' },
      { label: '参与者', value: '以早期核心人物为主，重点观察谁更快接受规则逻辑。' },
      { label: '后果', value: '人物开始区分“可靠的人”和“会把队伍带崩的人”。' },
      { label: '知识补充', value: '适合挂接概率决策、囚徒困境和群体恐慌扩散等知识条。' },
    ],
    tags: ['概率', '早期游戏', '信任筛选'],
    timeline: ['opening-bet'],
  },
  {
    id: 'mouse-game',
    type: 'event',
    title: '鼠类游戏',
    subtitle: '早期群体筛选样本',
    summary: '鼠类游戏把早期群体最原始的恐惧、趋利和互相试探直接摊开，是开局脉络的重要事件锚点。',
    sections: [
      { label: '规则', value: '以最小代价与最快站位检验参与者的判断。' },
      { label: '参与者', value: '齐夏、林檎、乔家劲、陈俊南与早期群体。' },
      { label: '后果', value: '队伍开始明确谁能稳住局势、谁会先失衡。' },
      { label: '意义', value: '它补足开局的第一批事件颗粒度。' },
    ],
    tags: ['鼠类', '筛选', '早期局'],
    timeline: ['opening-bet'],
  },
  {
    id: 'lie-screening',
    type: 'event',
    title: '说谎筛人',
    subtitle: '开局最锋利的站位筛选',
    summary: '说谎机制让最早期的人物就被迫站队，信任被改写成风险规避。',
    sections: [
      { label: '前因', value: '陌生人被同时推入封闭空间，秩序尚未成形。' },
      { label: '规则', value: '说谎与站位成为生死指标，信息差被迅速放大。' },
      { label: '后果', value: '队伍第一次出现“可信/不可信”的分层。' },
      { label: '意义', value: '为后续所有合作与背叛提供了最早期的依据。' },
    ],
    tags: ['说谎', '筛选', '站位'],
    timeline: ['opening-bet'],
  },
  {
    id: 'order-clash',
    type: 'event',
    title: '医生与警官秩序冲突',
    subtitle: '旧世界秩序第一次断裂',
    summary: '旧秩序的权威在终焉里无法复制，理性与权威的对抗被规则直接碾碎。',
    sections: [
      { label: '前因', value: '旧世界身份试图恢复原有秩序。' },
      { label: '规则', value: '规则不承认外部权威，只承认选择代价。' },
      { label: '后果', value: '人物意识到“身份”在终焉里失效。' },
      { label: '意义', value: '标志终焉从社会秩序转入规则秩序。' },
    ],
    tags: ['秩序冲突', '旧世界', '权威失效'],
    timeline: ['opening-bet'],
  },
  {
    id: 'renyang-game',
    type: 'event',
    title: '人羊游戏',
    subtitle: '人数与淘汰的第一次展示',
    summary: '人羊局把“人数规则”变成第一波实际淘汰压力，让队伍不得不接受筛选。',
    sections: [
      { label: '规则', value: '人数与淘汰规则叠加，站位的代价被显性化。' },
      { label: '参与者', value: '早期核心人物与普通参与者共同经历。' },
      { label: '后果', value: '临时合作被迫成形，弱势角色被更快抛弃。' },
      { label: '意义', value: '为后续层级化游戏打下最初的认知底座。' },
    ],
    tags: ['人羊', '人数规则', '淘汰压力'],
    timeline: ['opening-bet'],
  },
  {
    id: 'temporary-coop-event',
    type: 'event',
    title: '临时合作出现',
    subtitle: '先一起活，再谈信任',
    summary: '合作先于信任出现，人物第一次以“最低风险”逻辑形成站位。',
    sections: [
      { label: '前因', value: '初始局的高压迫使人物寻找可控同伴。' },
      { label: '规则', value: '合作是风险对冲，不是情感共识。' },
      { label: '后果', value: '主角团雏形开始浮现，协作边界被划定。' },
      { label: '意义', value: '为后续共犯结构与背叛埋下伏笔。' },
    ],
    tags: ['临时合作', '风险对冲', '队伍雏形'],
    timeline: ['opening-bet'],
  },
  {
    id: 'false-alliance-event',
    type: 'event',
    title: '伪同盟成形',
    subtitle: '合作与背叛的灰区',
    summary: '抱团开始出现，但每个人都在计算自己什么时候该先转身。',
    sections: [
      { label: '前因', value: '第一轮生存压力迫使人物必须暂时结盟。' },
      { label: '规则', value: '合作先于信任成立，任何站位都带着随时会崩开的灰色边界。' },
      { label: '后果', value: '主角团开始在彼此怀疑中形成更复杂的默契。' },
      { label: '意义', value: '团队不是稳定组织，而是持续震荡中的共犯网络。' },
    ],
    tags: ['联盟', '背叛', '震荡结构'],
    timeline: ['false-alliance'],
  },
  {
    id: 'trust-reorder-event',
    type: 'event',
    title: '关系震荡与重排',
    subtitle: '站位不断被撕裂重建',
    summary: '事件不断挤压人物选择，旧合作被撕裂，新组合被迫重建。',
    sections: [
      { label: '前因', value: '伪同盟的灰区持续扩大，规则挤压加重。' },
      { label: '规则', value: '背叛与重组成了稳定机制，而非偶然事故。' },
      { label: '后果', value: '队伍结构更复杂，真正核心人物被筛出。' },
      { label: '意义', value: '把人物关系推向“结构化共犯网络”。' },
    ],
    tags: ['关系重排', '背叛', '共犯结构'],
    timeline: ['false-alliance'],
  },
  {
    id: 'earth-snake',
    type: 'event',
    title: '地蛇问答局',
    subtitle: '提问与反问成为刀',
    summary: '从这一局开始，人物对规则的理解不再停留在解题，而进入对语义、表情和隐藏裁量权的争夺。',
    sections: [
      { label: '规则', value: '问答、站位与多数/少数逻辑叠加，使语义缝隙成为真正战场。' },
      { label: '参与者', value: '中段核心人物与阵营成员，适合观察关系如何被规则压到极限。' },
      { label: '后果', value: '队伍内部分工进一步稳定，但信任也进一步变脏。' },
      { label: '知识补充', value: '适合挂接语言博弈、信息差与多数暴政。' },
    ],
    tags: ['地蛇', '问答', '语言博弈'],
    timeline: ['echo-awakening'],
  },
  {
    id: 'diji-game',
    type: 'event',
    title: '地鸡游戏',
    subtitle: '早期房间型高压节点',
    summary: '地鸡局强化房间事件与角色命运绑定，让规则不再只是问题而是命运枷锁。',
    sections: [
      { label: '规则', value: '房间机制与时间压力叠加，胜负被迅速定格。' },
      { label: '参与者', value: '中前期核心人物与关键配角。' },
      { label: '后果', value: '人物心理开始呈现稳定分层。' },
      { label: '意义', value: '为后续生肖体系的压迫感做预演。' },
    ],
    tags: ['地鸡', '房间局', '高压'],
    timeline: ['echo-awakening'],
  },
  {
    id: 'human-snake-quiz',
    type: 'event',
    title: '人蛇·问答游戏',
    subtitle: '规则理解被继续放大',
    summary: '它让人物对规则的理解继续升级，也使团队内部的判断力与风险承担重新分层。',
    sections: [
      { label: '前因', value: '经过第一轮破局之后，人物开始主动迎向更复杂的生肖游戏。' },
      { label: '规则', value: '规则不再只是题目，而是主持者对人物心理和语言的进一步操控。' },
      { label: '后果', value: '队伍开始出现更明确的认知分工与信任落差。' },
      { label: '意义', value: '它证明破局不是偶然，而是人物能力的持续累积。' },
    ],
    tags: ['生肖游戏', '认知升级', '队伍分层'],
    timeline: ['echo-awakening'],
  },
  {
    id: 'monkey-game',
    type: 'event',
    title: '人猴游戏',
    subtitle: '反应与判断的中段测试',
    summary: '人猴游戏把反应、直觉和群体判断拉到更高强度，推动主角团从试探走向更稳的协作。',
    sections: [
      { label: '规则', value: '反应与判断绑定，任何迟疑都可能直接改变结果。' },
      { label: '参与者', value: '齐夏、乔家劲、林檎以及中段核心人物。' },
      { label: '后果', value: '人物的执行能力和判断力被进一步分层。' },
      { label: '意义', value: '它是回响与智斗进一步结合的过渡事件。' },
    ],
    tags: ['人猴', '反应', '中段测试'],
    timeline: ['echo-awakening'],
  },
  {
    id: 'yunyao-echo',
    type: 'event',
    title: '云瑶的回响',
    subtitle: '强运外化',
    summary: '云瑶的回响让偶然性与运势从角色气质变成可见力量，也让天堂口的人物结构更有波动。',
    sections: [
      { label: '规则', value: '运势与人物处境被绑定，结果不再完全由单一推理决定。' },
      { label: '参与者', value: '云瑶、楚天秋、天堂口相关人物。' },
      { label: '后果', value: '天堂口内部的稳定感被进一步打散。' },
      { label: '意义', value: '它是人物能力与组织结构同时升级的节点。' },
    ],
    tags: ['云瑶', '回响', '强运'],
    timeline: ['echo-awakening', 'paradise-mouth'],
  },
  {
    id: 'echo-awakening-event',
    type: 'event',
    title: '回响外化',
    subtitle: '伤痕开始变成能力',
    summary: '回响把极端压力下的人格裂口直接外化，也把故事从生存局推成了世界结构局。',
    sections: [
      { label: '规则', value: '能力与创伤、执念、记忆紧密绑定，不是传统外挂。' },
      { label: '参与者', value: '主角团与关键配角都开始在能力层面被重新分层。' },
      { label: '后果', value: '谁能保留记忆、谁能继续成长，开始决定后续大局。' },
      { label: '知识补充', value: '适合挂接人格外化、创伤反应和异能叙事的差异。' },
    ],
    tags: ['回响', '能力觉醒', '人格外化'],
    timeline: ['echo-awakening'],
  },
  {
    id: 'paradise-mouth-event',
    type: 'event',
    title: '诡异的天堂口',
    subtitle: '生存开始组织化',
    summary: '故事在这里从单局求生转向组织化生存，人物关系从个体协作升级成阵营管理。',
    sections: [
      { label: '规则', value: '资源、信息与人手开始被组织方式统一调动。' },
      { label: '参与者', value: '楚天秋、文巧云、云瑶、张山等人物成为结构层核心。' },
      { label: '后果', value: '主角团第一次拥有真正意义上的阵营对照。' },
      { label: '知识补充', value: '适合挂接组织治理、家人话术与服从机制。' },
    ],
    tags: ['天堂口', '组织化生存', '阵营'],
    timeline: ['paradise-mouth'],
  },
  {
    id: 'family-expansion',
    type: 'event',
    title: '家人扩张',
    subtitle: '天堂口的共同体话术扩大',
    summary: '家人话术把天堂口从组织语汇推进成情感规训装置，也让“共同体”更具压迫性。',
    sections: [
      { label: '前因', value: '天堂口需要更强的内部粘合方式。' },
      { label: '规则', value: '把组织忠诚包装成家庭关系。' },
      { label: '后果', value: '保护、利用和服从开始更难拆开。' },
      { label: '意义', value: '它是天堂口最关键的组织叙事节点之一。' },
    ],
    tags: ['家人话术', '共同体', '天堂口'],
    timeline: ['paradise-mouth'],
  },
  {
    id: 'liangren-king',
    type: 'event',
    title: '良人王',
    subtitle: '天堂口合法性的回收节点',
    summary: '“良人王”把楚天秋的组织魅力、领袖神话与治理裂缝同时拉到台面，天堂口由此不再只是避难团体。',
    sections: [
      { label: '前因', value: '天堂口扩张后，需要一套能够解释服从、保护与牺牲的内部叙事。' },
      { label: '规则', value: '领袖声望被包装成组织合法性，名声开始参与治理。' },
      { label: '后果', value: '楚天秋从强者升级成真正的组织型核心，也因此更容易暴露裂缝。' },
      { label: '意义', value: '它是天堂口从生存组织跃迁为政治结构的关键事件。' },
    ],
    tags: ['良人王', '楚天秋', '组织合法性'],
    timeline: ['paradise-mouth'],
  },
  {
    id: 'jidao-appearance',
    type: 'event',
    title: '极道现身',
    subtitle: '反抗从隐线进入主舞台',
    summary: '极道现身意味着反抗不再是零散动作，而成为可以被识别和追踪的组织力量。',
    sections: [
      { label: '前因', value: '更早期的反抗和积累终于形成显性组织。' },
      { label: '规则', value: '组织比单人更能对抗结构压迫。' },
      { label: '后果', value: '极道与天堂口形成清晰对照。' },
      { label: '意义', value: '让反抗线第一次真正具备群像厚度。' },
    ],
    tags: ['极道', '现身', '组织化'],
    timeline: ['paradise-mouth', 'dragon-collapse'],
  },
  {
    id: 'faction-formation',
    type: 'event',
    title: '参与者阵营成形',
    subtitle: '从个体协作到阵营博弈',
    summary: '人物不再只是个体合作，而是被迫站进更大的阵营逻辑。',
    sections: [
      { label: '前因', value: '天堂口、极道等组织化生存开始成形。' },
      { label: '规则', value: '阵营逻辑把个人选择变成群体选择。' },
      { label: '后果', value: '冲突从人物对升级为阵营对。' },
      { label: '意义', value: '为终局结构战奠定组织基础。' },
    ],
    tags: ['阵营', '组织', '对抗'],
    timeline: ['paradise-mouth'],
  },
  {
    id: 'jidao-rise',
    type: 'event',
    title: '极道崛起',
    subtitle: '反抗线被推上前台',
    summary: '燕知春与江若雪等人的行动把终焉里的反抗从局部行为升级成组织性动员。',
    sections: [
      { label: '规则', value: '极道靠共同信念先压住内部差异，再用组织行动对抗更高层秩序。' },
      { label: '参与者', value: '燕知春、江若雪、周末等极道人物。' },
      { label: '后果', value: '关系张力从人物对扩张为团体与团体之间的碰撞。' },
      { label: '知识补充', value: '适合挂接群体动员、领袖神话与组织离心。' },
    ],
    tags: ['极道', '组织行动', '领袖神话'],
    timeline: ['dragon-collapse'],
  },
  {
    id: 'rebellion-day',
    type: 'event',
    title: '叛乱日',
    subtitle: '反抗从态度变成行动',
    summary: '乔家劲决定去救人，使反抗线第一次以实际行动打破观望状态，极道从理念进入了必须承担代价的阶段。',
    sections: [
      { label: '前因', value: '天堂口与极道的路线差异越来越清楚，旁观已经无法维持。' },
      { label: '规则', value: '一旦去救人，阵营冲突和更高层追杀就会被同步触发。' },
      { label: '后果', value: '极道不再是边缘噪声，而成为主线中的实际行动力量。' },
      { label: '意义', value: '它把“反抗”从口号推进成了真实事件链。' },
    ],
    tags: ['叛乱日', '极道', '乔家劲'],
    timeline: ['paradise-mouth', 'dragon-collapse'],
  },
  {
    id: 'dragon-collapse-event',
    type: 'event',
    title: '双龙裂痕与神兽坍塌',
    subtitle: '上位秩序第一次显著失稳',
    summary: '从这一段开始，终焉不再只是参与者对抗游戏，而是不同治理方案争夺桃源解释权。',
    sections: [
      { label: '规则', value: '天级、神兽和参与者之间的层级关系开始显著松动。' },
      { label: '参与者', value: '青龙、天龙、齐夏、楚天秋、乔家劲、张山等。' },
      { label: '后果', value: '局部关卡叙事正式跃迁为政权和结构叙事。' },
      { label: '知识补充', value: '适合挂接权力真空、双核政治和制度裂缝。' },
    ],
    tags: ['双龙', '神兽', '结构崩塌'],
    timeline: ['dragon-collapse'],
  },
  {
    id: 'zodiac-confrontation',
    type: 'event',
    title: '参与者对抗生肖体系',
    subtitle: '规则与反抗正面撞击',
    summary: '参与者开始主动反攻生肖体系，规则不再只是压迫工具，而成为对抗对象。',
    sections: [
      { label: '前因', value: '阵营成形与回响升级提供了反抗基础。' },
      { label: '规则', value: '生肖体系被拆解为可被对抗的结构单元。' },
      { label: '后果', value: '权力格局开始真正松动。' },
      { label: '意义', value: '推动故事从闯关走向结构战争。' },
    ],
    tags: ['对抗', '生肖', '结构战争'],
    timeline: ['dragon-collapse'],
  },
  {
    id: 'zodiac-bet-contract',
    type: 'event',
    title: '生肖飞升对赌合同',
    subtitle: '层级跃迁的制度化',
    summary: '飞升不只是奖励，而是拿命和命运做对赌的制度化协议。',
    sections: [
      { label: '规则', value: '飞升与收益、权限、代价绑定。' },
      { label: '参与者', value: '白羊、青龙、天龙及上层结构相关人物。' },
      { label: '后果', value: '层级不再是自然秩序，而是可交易、可压迫的协议。' },
      { label: '意义', value: '把生肖系统和权力系统焊在一起。' },
    ],
    tags: ['飞升', '对赌', '生肖'],
    timeline: ['dragon-collapse', 'white-sheep-path'],
  },
  {
    id: 'final-train',
    type: 'event',
    title: '列车与第二站',
    subtitle: '真相与终局的收束点',
    summary: '列车、第二站与最终决战相互缠绕，让终焉之地的真相、人物选择与最终代价完成闭环。',
    sections: [
      { label: '前因', value: '长期布局、组织对抗与真相逼近共同把所有人推向终局。' },
      { label: '规则', value: '赢法不再是通过关卡，而是重新定义什么才算胜利。' },
      { label: '后果', value: '世界结构被改写，人物命运得到终极重估。' },
      { label: '意义', value: '它是整部作品从生存博弈转向世界重构的关键门槛。' },
    ],
    tags: ['终局', '列车', '第二站'],
    timeline: ['final-gate-approach', 'final-gate'],
  },
  {
    id: 'giant-clock-event',
    type: 'event',
    title: '巨钟与第二站入口',
    subtitle: '终局空间的开启装置',
    summary: '巨钟是终局空间层级的开启装置，推动叙事从胜负走向结构跃迁。',
    sections: [
      { label: '规则', value: '空间层级被显性化，胜利被迫与空间结构绑定。' },
      { label: '后果', value: '人物进入真正意义上的终局区域。' },
      { label: '意义', value: '列车事件从交通节点升级为结构节点。' },
    ],
    tags: ['巨钟', '第二站', '空间跃迁'],
    timeline: ['final-gate-approach', 'final-gate'],
  },
  {
    id: 'middle-station',
    type: 'event',
    title: '中间站',
    subtitle: '终局过渡空间',
    summary: '中间站把局部胜负暂时悬置，让故事进入空间层、时间层和解释层的过渡地带。',
    sections: [
      { label: '前因', value: '多轮对抗后，人物需要一个过渡到终局的空间。' },
      { label: '规则', value: '不是单局胜负，而是过渡与转移。' },
      { label: '后果', value: '列车、第二站和终局秩序变得可见。' },
      { label: '意义', value: '它是终局空间叙事的重要中转点。' },
    ],
    tags: ['中间站', '过渡', '空间层'],
    timeline: ['final-gate-approach', 'final-gate'],
  },
  {
    id: 'how-win',
    type: 'event',
    title: '如何获胜',
    subtitle: '终局胜利条件被重写',
    summary: '这不是告诉角色怎么赢，而是告诉读者“赢”已经被世界规则重新定义。',
    sections: [
      { label: '规则', value: '胜利条件从完成任务变成承担代价。' },
      { label: '后果', value: '价值判断压过了关卡判断。' },
      { label: '意义', value: '终局真正进入哲学层。' },
    ],
    tags: ['如何获胜', '终局', '重定义'],
    timeline: ['final-gate-approach', 'final-gate'],
  },
  {
    id: 'win-method',
    type: 'event',
    title: '赢法',
    subtitle: '终局里的策略骨架',
    summary: '赢法不再只是通关技巧，而是把最后一段路线、代价与选择重新焊接成一套可执行结构。',
    sections: [
      { label: '规则', value: '胜利不再依赖单一局部技巧，而依赖整段路线与代价配比。' },
      { label: '后果', value: '角色必须为“赢”支付结构性代价。' },
      { label: '意义', value: '它让终局的“怎么赢”与“赢了算什么”分离。' },
    ],
    tags: ['赢法', '策略', '终局'],
    timeline: ['final-gate-approach', 'final-gate'],
  },
  {
    id: 'dissociation',
    type: 'event',
    title: '离析',
    subtitle: '旧秩序被拆散',
    summary: '离析意味着顶层秩序不再是整块铁板，而开始被撕开、拆散、重新拼装。',
    sections: [
      { label: '规则', value: '结构分离与失控同步发生。' },
      { label: '后果', value: '天龙和青龙所维持的旧框架开始崩解。' },
      { label: '意义', value: '为新世界构造腾出空间。' },
    ],
    tags: ['离析', '旧秩序', '拆解'],
    timeline: ['final-gate-approach', 'final-gate'],
  },
  {
    id: 'shengshengbuxi',
    type: 'event',
    title: '生生不息',
    subtitle: '复活悖论的终局化',
    summary: '生生不息把回响、复活与世界连续性连成一条线，是最终解释的关键支点。',
    sections: [
      { label: '规则', value: '连续性不再依赖记忆完整，而依赖结构回收。' },
      { label: '后果', value: '人物命运和世界重构发生最终对接。' },
      { label: '意义', value: '它是全站首页文案与终局事件的核心支点。' },
    ],
    tags: ['生生不息', '复活', '终局支点'],
    timeline: ['final-gate'],
  },
  {
    id: 'truth-approach-event',
    type: 'event',
    title: '真相逼近',
    subtitle: '求生线转向认知线',
    summary: '人物不再只问“怎么活”，而开始追问“这是什么”。',
    sections: [
      { label: '前因', value: '回响升级与阵营碰撞催生认知需求。' },
      { label: '规则', value: '规则被视为真相入口而非障碍。' },
      { label: '后果', value: '人物线与世界线开始汇流。' },
      { label: '意义', value: '终局叙事从生存转向解释。' },
    ],
    tags: ['真相', '认知线', '汇流'],
    timeline: ['dragon-collapse'],
  },
  {
    id: 'empty-house-awakening',
    type: 'event',
    title: '空屋苏醒与开局定调',
    subtitle: '最小世界模型建立',
    summary: '空屋苏醒、说谎筛人、秩序冲突与第一次死亡，构成终焉的最小社会结构。',
    sections: [
      { label: '前因', value: '旧秩序碎裂，人物被投放到极简规则空间。' },
      { label: '规则', value: '说谎与站位决定存活，秩序冲突被推上台面。' },
      { label: '后果', value: '人物迅速意识到“讲道理”无效，规则才是唯一公理。' },
      { label: '意义', value: '这一段把终焉从“危机”变成“制度”。' },
    ],
    tags: ['开局', '说谎', '秩序冲突'],
    timeline: ['prelude-memory'],
  },
  {
    id: 'first-death-loop',
    type: 'event',
    title: '首轮死亡与循环揭示',
    subtitle: '终焉从死亡威胁变成循环制度',
    summary: '第一次死亡与复活确认了“终局并非结束”，而是循环式管理。',
    sections: [
      { label: '前因', value: '人物以为死亡即终点。' },
      { label: '规则', value: '死亡与复活被制度化，记忆被切割。' },
      { label: '后果', value: '生存压力转化为长期治理压力。' },
      { label: '意义', value: '终焉开始显现为可持续运转的统治系统。' },
    ],
    tags: ['循环', '复活', '制度'],
    timeline: ['opening-bet'],
  },
  {
    id: 'probability-training',
    type: 'event',
    title: '概率型早期训练场',
    subtitle: '人鼠、人猪等赌命局',
    summary: '概率型游戏把恐惧、胜率判断与群体心理一起推上台面。',
    sections: [
      { label: '规则', value: '概率决策与侥幸心理交织，理性被迫与恐惧同场竞技。' },
      { label: '参与者', value: '早期核心人物与高压局面中的普通参与者。' },
      { label: '后果', value: '人物开始区分“可靠判断者”和“拖垮队伍的人”。' },
      { label: '意义', value: '早期赌命局是所有后续博弈判断的训练场。' },
    ],
    tags: ['概率', '赌命', '早期训练'],
    timeline: ['opening-bet'],
  },
  {
    id: 'moral-shift',
    type: 'event',
    title: '道德与生存切换',
    subtitle: '价值观的第一次断裂',
    summary: '角色从“讲道理”转向“先活下去”，合作关系随即被重写。',
    sections: [
      { label: '前因', value: '初期合作建立在模糊道德共识上。' },
      { label: '规则', value: '规则压迫让道德成为成本，生存成为唯一合法目标。' },
      { label: '后果', value: '关系结构从道德认同转为利益结盟。' },
      { label: '意义', value: '是人物心理转轨的关键节点。' },
    ],
    tags: ['价值观转向', '心理转轨', '结盟'],
    timeline: ['false-alliance'],
  },
  {
    id: 'core-ensemble',
    type: 'event',
    title: '主角团雏形形成',
    subtitle: '认知、执行与串联稳定分工',
    summary: '主角团由临时站位转为结构性合作，开始成为事件中的稳定核心。',
    sections: [
      { label: '前因', value: '伪同盟与高压事件不断重排站位。' },
      { label: '规则', value: '分工来自风险最小化而非信任。' },
      { label: '后果', value: '主角团成为后续所有事件的叙事轴心。' },
      { label: '意义', value: '从个体求生迈向结构协作。' },
    ],
    tags: ['主角团', '分工', '协作结构'],
    timeline: ['false-alliance'],
  },
  {
    id: 'information-gap',
    type: 'event',
    title: '信息差与规则缝隙',
    subtitle: '智斗母题成形',
    summary: '信息差、规则漏洞与胜利条件误判，成为前中期最关键的智斗母题。',
    sections: [
      { label: '规则', value: '胜利条件被故意模糊，信息成为最重要的稀缺资源。' },
      { label: '后果', value: '人物以“谁掌握信息”重新分层。' },
      { label: '意义', value: '把事件从体力局推向认知局。' },
    ],
    tags: ['信息差', '规则缝隙', '智斗'],
    timeline: ['echo-awakening'],
  },
  {
    id: 'zodiac-system',
    type: 'event',
    title: '生肖游戏总体系',
    subtitle: '事件制度化的全局框架',
    summary: '人、地、天三级与多生肖联动，使事件从单局升级为制度化筛选。',
    sections: [
      { label: '规则', value: '不同层级决定参与者接近真相与权力的距离。' },
      { label: '后果', value: '人物关系被层级制度持续筛选与重排。' },
      { label: '意义', value: '终焉从事件集合变成系统性秩序。' },
    ],
    tags: ['生肖体系', '层级', '制度'],
    timeline: ['echo-awakening'],
  },
  {
    id: 'high-pressure-quiz',
    type: 'event',
    title: '高压问答局群',
    subtitle: '地鸡、地蛇、人蛇等',
    summary: '问答、少数与多数、表情与语义成为武器，关系被规则压到极限。',
    sections: [
      { label: '规则', value: '语义缝隙和少数/多数逻辑反复拉扯。' },
      { label: '后果', value: '团队内部分工稳定但信任进一步变脏。' },
      { label: '意义', value: '展示规则如何直接塑形人物心理。' },
    ],
    tags: ['问答局', '语言博弈', '高压'],
    timeline: ['echo-awakening'],
  },
  {
    id: 'bliss-bank',
    type: 'event',
    title: '极乐钱庄与收益模型',
    subtitle: '规则经济化的集中体现',
    summary: '收益、权力分配与白羊收益模型让规则从惩罚机制升级为经济系统。',
    sections: [
      { label: '规则', value: '收益和权力绑定，规则成为财富与地位的生产器。' },
      { label: '后果', value: '阵营之间的竞争从生存转为资源争夺。' },
      { label: '意义', value: '终焉开始拥有经济学维度。' },
    ],
    tags: ['收益', '钱庄', '白羊'],
    timeline: ['paradise-mouth'],
  },
  {
    id: 'white-sheep-ascent',
    type: 'event',
    title: '白羊之路',
    subtitle: '顶层秩序的入口事件',
    summary: '白羊晋升为天，标志剧情进入权力顶层与秩序核心。',
    sections: [
      { label: '规则', value: '身份跃迁不仅是权力变化，也是叙事层级跃迁。' },
      { label: '后果', value: '天级秩序开始暴露裂缝。' },
      { label: '意义', value: '从阵营博弈转向秩序对抗。' },
    ],
    tags: ['白羊', '晋升', '顶层秩序'],
    timeline: ['dragon-collapse', 'white-sheep-path'],
  },
  {
    id: 'tianma-principle',
    type: 'event',
    title: '天马原理',
    subtitle: '高位规则开始显影',
    summary: '看不见的丝线、粉末化的接触失败和“天马时刻”共同说明，终焉已经不再靠房间规则维持，而靠更高层的管理框架维持。',
    sections: [
      { label: '前因', value: '阵营、回响和长期布局都成熟之后，人物开始直接触碰更高层的管理逻辑。' },
      { label: '规则', value: '真正的压迫不一定看得见，但会以系统性方式阻止参与者越界。' },
      { label: '后果', value: '终焉开始被明确理解为治理系统，而不仅是关卡合集。' },
      { label: '意义', value: '它是事件馆与世界观馆之间的重要桥接节点。' },
    ],
    tags: ['天马', '高位规则', '治理机制'],
    timeline: ['dragon-collapse', 'white-sheep-path'],
  },
  {
    id: 'beast-oppression',
    type: 'event',
    title: '龙类与神兽压迫',
    subtitle: '上位秩序的持续压制',
    summary: '青龙、天龙与神兽体系使后期从“局”进入“上位秩序压迫”。',
    sections: [
      { label: '规则', value: '上位者以制度压迫而非单局规则控制参与者。' },
      { label: '后果', value: '终焉结构显露为统治系统，而非游戏集合。' },
      { label: '意义', value: '把故事推向结构战争。' },
    ],
    tags: ['青龙', '天龙', '神兽'],
    timeline: ['dragon-collapse', 'dragon-fracture'],
  },
  {
    id: 'qinglong-downfall',
    type: 'event',
    title: '青龙翻盘与上位结构松动',
    subtitle: '旧秩序实质松动',
    summary: '天级陨落与青龙失势标志旧秩序开始被真正撼动。',
    sections: [
      { label: '规则', value: '上位秩序的稳定被高压事件击穿。' },
      { label: '后果', value: '制度性压迫开始出现裂口。' },
      { label: '意义', value: '从结构压迫迈向结构崩塌。' },
    ],
    tags: ['青龙', '失势', '秩序松动'],
    timeline: ['dragon-collapse', 'dragon-fracture'],
  },
  {
    id: 'mandela-effect',
    type: 'event',
    title: '曼德拉效应',
    subtitle: '现实感开始整体漂移',
    summary: '记忆、关系和自我叙述出现微小但集体化的错位，终局前“什么才算真实”被提前抬到了主舞台。',
    sections: [
      { label: '前因', value: '白羊之路与上位秩序松动之后，人物开始频繁触碰记忆和现实的裂缝。' },
      { label: '规则', value: '终焉不仅能重排事件，也能重排人的现实感与自我叙述。' },
      { label: '后果', value: '终局被进一步推向对现实定义权的争夺。' },
      { label: '意义', value: '它是通往梦境现实与最终真相的前置事件。' },
    ],
    tags: ['曼德拉效应', '现实感', '记忆错位'],
    timeline: ['dragon-fracture', 'final-gate-approach'],
  },
  {
    id: 'tianlong-dissociation',
    type: 'event',
    title: '天龙离析与全域清场',
    subtitle: '终局前的最大清算',
    summary: '天龙发动离析与清场，胜利条件被改写，故事走向世界重构。',
    sections: [
      { label: '规则', value: '全域清场把生存问题直接推成结构问题。' },
      { label: '后果', value: '终局进入“如何改写规则”的阶段。' },
      { label: '意义', value: '终局前最后一层主事件。' },
    ],
    tags: ['天龙', '离析', '清场'],
    timeline: ['dragon-fracture', 'final-gate-approach'],
  },
  {
    id: 'endgame-rewrite',
    type: 'event',
    title: '终局重写胜利条件',
    subtitle: '胜利被重新定义',
    summary: '终局不再是通关，而是改写“什么才算赢”。',
    sections: [
      { label: '规则', value: '规则被重写，胜利从结果转为价值选择。' },
      { label: '后果', value: '人物必须承担更大的价值与责任代价。' },
      { label: '意义', value: '把终焉从闯关叙事推成世界重构叙事。' },
    ],
    tags: ['终局', '胜利条件', '重写'],
    timeline: ['final-gate'],
  },
  {
    id: 'immortality-paradox',
    type: 'event',
    title: '生生不息复活悖论',
    subtitle: '救赎与惩罚的同一性',
    summary: '复活既是救赎也是惩罚，死亡被重写成治理工具。',
    sections: [
      { label: '规则', value: '复活成为长期管理机制而非希望。' },
      { label: '后果', value: '人物对“活着”的意义产生分裂。' },
      { label: '意义', value: '将终局价值观拉向哲学层。' },
    ],
    tags: ['复活', '悖论', '生生不息'],
    timeline: ['final-gate'],
  },
  {
    id: 'endgame-ethos',
    type: 'event',
    title: '终局价值观落点',
    subtitle: '选择被重写成信念',
    summary: '不再以牺牲换自由，价值观在第十一天的阳光里被收束。',
    sections: [
      { label: '规则', value: '选择成为意义本身，而不是通关手段。' },
      { label: '后果', value: '故事价值落点明确，人物弧线闭合。' },
      { label: '意义', value: '终局从博弈转为价值回收。' },
    ],
    tags: ['价值观', '终局', '第十一天'],
    timeline: ['final-gate'],
  },
  {
    id: 'reset-resonance',
    type: 'event',
    title: '未完成回收与重置解释',
    subtitle: '结局的余震',
    summary: '终局并非复原，而是重置，伏笔以余震形式继续保留。',
    sections: [
      { label: '规则', value: '重置意味着真相仍留空白。' },
      { label: '后果', value: '叙事留下余震感和开放性。' },
      { label: '意义', value: '让终焉世界拥有继续延展的空间。' },
    ],
    tags: ['重置', '余震', '未回收'],
    timeline: ['final-gate'],
  },
  {
    id: 'qixia-variable',
    type: 'event',
    title: '齐夏变量与神性问题',
    subtitle: '终局解释框架',
    summary: '终局事件最终回收为齐夏作为变量、神性与欺诈并存的解释框架。',
    sections: [
      { label: '规则', value: '变量意味着系统无法完全封闭。' },
      { label: '后果', value: '人物线与真相线合并。' },
      { label: '意义', value: '终局解释回到主角个体。' },
    ],
    tags: ['齐夏', '变量', '神性'],
    timeline: ['final-gate'],
  },
  {
    id: 'prehistory-layout',
    type: 'event',
    title: '前史布局与长线预设',
    subtitle: '故事真正的起点',
    summary: '事件链并非从第一天开始，而是从更长的前史布局与失败开始。',
    sections: [
      { label: '前因', value: '旧世界的失败与押送，让终焉成为必然。' },
      { label: '规则', value: '多时间线布局提前埋下终局结构。' },
      { label: '后果', value: '终焉的“偶然性”被彻底推翻。' },
      { label: '意义', value: '故事起点被拉长到历史层面。' },
    ],
    tags: ['前史', '布局', '长线'],
    timeline: ['prelude-memory'],
  },
  {
    id: 'rules',
    type: 'rule',
    title: '游戏规则',
    subtitle: '操控关系的隐藏齿轮',
    summary: '规则不是背景，而是不断重排人物关系和事件走向的主动力量。',
    sections: [
      { label: '作用', value: '把人变成节点，把选择变成代价。' },
      { label: '影响', value: '人物之间的关系强弱往往由规则压力决定。' },
      { label: '探索价值', value: '它解释了为何同一个人会在不同事件中完全换位。' },
    ],
    tags: ['规则', '代价', '结构力量'],
    timeline: ['opening-bet', 'echo-awakening', 'final-gate'],
  },
  {
    id: 'echo',
    type: 'rule',
    title: '回响',
    subtitle: '创伤与执念的外化接口',
    summary: '回响不只是能力设定，它决定谁能保留历史连续性，谁能从被刷新的人口变成真正的历史主体。',
    sections: [
      { label: '作用', value: '把极端情绪与人格裂口转化为可执行能力。' },
      { label: '影响', value: '能力越强，往往越难回到普通人生逻辑。' },
      { label: '探索价值', value: '它把人物馆与世界观馆直接缝在一起。' },
    ],
    tags: ['回响', '记忆', '能力体系'],
    timeline: ['echo-awakening', 'final-gate'],
  },
  {
    id: 'cycle',
    type: 'rule',
    title: '十日循环',
    subtitle: '复活与失忆组成的管理周期',
    summary: '它不是单纯时间回档，而是一整套持续清洗、持续重投、持续维稳的制度周期。',
    sections: [
      { label: '作用', value: '把死亡从终点改造成统治者可反复调用的管理工具。' },
      { label: '影响', value: '让普通参与者始终活在没有连续历史的状态里。' },
      { label: '探索价值', value: '它解释了为什么终焉最大的压迫来自停滞而非瞬间死亡。' },
    ],
    tags: ['十日', '轮回', '复活'],
    timeline: ['prelude-memory', 'opening-bet', 'final-gate'],
  },
  {
    id: 'tiers',
    type: 'rule',
    title: '天·地·人层级',
    subtitle: '难度分层也是权力分层',
    summary: '人、地、天三级游戏不仅区分危险程度，也区分人物距离真相还有多远。',
    sections: [
      { label: '作用', value: '控制参与者接触真相和接触权力核心的距离。' },
      { label: '影响', value: '越往上走，敌人越像制度本身。' },
      { label: '探索价值', value: '它让事件馆不只是房间合集，而是层级化秩序样本。' },
    ],
    tags: ['层级', '生肖', '权力距离'],
    timeline: ['echo-awakening', 'dragon-collapse'],
  },
  {
    id: 'dao',
    type: 'rule',
    title: '三千六百道',
    subtitle: '被精确包装的希望神话',
    summary: '“集齐三千六百道即可离开”的说法是终焉里最重要的合法性叙事之一。',
    sections: [
      { label: '作用', value: '让参与者相信系统存在可计算出口。' },
      { label: '影响', value: '希望本身变成持续参与制度的燃料。' },
      { label: '探索价值', value: '它是判断终焉之地到底是救赎还是骗局的关键口子。' },
    ],
    tags: ['道', '出口神话', '合法性'],
    timeline: ['opening-bet', 'echo-awakening', 'final-gate'],
  },
  {
    id: 'endland',
    type: 'truth',
    title: '终焉之地',
    subtitle: '被规则覆盖的世界壳层',
    summary: '它不是单一地点，而是统摄全部人物、事件和规则的外层结构。',
    sections: [
      { label: '作用', value: '把人物困在一个不断被规则和选择重写的世界中。' },
      { label: '影响', value: '所有事件都不是孤立发生，而是在它的框架内被塑形。' },
      { label: '探索价值', value: '它是从人物线跳向真相线的核心中转节点。' },
    ],
    tags: ['世界壳层', '真相入口', '系统性压迫'],
    timeline: ['opening-bet', 'echo-awakening', 'paradise-mouth', 'final-gate'],
  },
  {
    id: 'taoyuan',
    type: 'truth',
    title: '桃源计划',
    subtitle: '终焉之前的原始命名',
    summary: '桃源意味着这个世界可能一开始并不是为了制造纯粹杀戮，而是某种被劫持、被篡改的计划。',
    sections: [
      { label: '作用', value: '把终焉从纯地狱叙事拖回人造空间叙事。' },
      { label: '影响', value: '终焉与桃源之间的落差，构成了真相层最关键的裂缝。' },
      { label: '探索价值', value: '它直接连接结构层和真相层。' },
    ],
    tags: ['桃源', '原始计划', '命名裂缝'],
    timeline: ['prelude-memory', 'paradise-mouth', 'final-gate'],
  },
  {
    id: 'dream-reality',
    type: 'truth',
    title: '梦境现实',
    subtitle: '现实感可被持续伪造',
    summary: '终局最重要的反转之一，是人物最终面对的不是“如何出去”，而是“什么才配叫现实”。',
    sections: [
      { label: '作用', value: '把所有前期逃生叙事改写成对现实感本身的争夺。' },
      { label: '影响', value: '余念安、齐夏与终局选择都被拖入这一层。' },
      { label: '探索价值', value: '它是世界观馆最适合承载争议和重解释的节点。' },
    ],
    tags: ['梦境', '现实', '认知哲学'],
    timeline: ['final-gate'],
  },
  {
    id: 'new-world',
    type: 'truth',
    title: '新世界构造',
    subtitle: '成神不是拿到权限，而是造出细部',
    summary: '终局里最重要的不是击败谁，而是谁愿意为他人承担漫长的世界建造工程。',
    sections: [
      { label: '作用', value: '把终局从杀王叙事提升为世界重构叙事。' },
      { label: '影响', value: '齐夏的孤独、天龙的失败和众人的奔流向前在这里闭合。' },
      { label: '探索价值', value: '它是人物馆、事件馆和世界观馆共同汇流的终点。' },
    ],
    tags: ['新世界', '成神', '终局回收'],
    timeline: ['final-gate'],
  },
  {
    id: 'survival-alliance',
    type: 'faction',
    title: '主角团共犯网络',
    subtitle: '不是同伴，而是互相拖拽着活下去',
    summary: '这不是传统意义上的团队，而是一组在极端环境中被迫形成的高压协作网络。',
    sections: [
      { label: '构成', value: '以齐夏为认知中心，围绕林檎、乔家劲、陈俊南等人不断重排。' },
      { label: '特点', value: '合作、怀疑、利用、保护同时存在。' },
      { label: '探索价值', value: '几乎所有有意思的关系链都能从这里向外扩散。' },
    ],
    tags: ['团队结构', '共犯', '高压协作'],
    timeline: ['opening-bet', 'false-alliance', 'echo-awakening', 'final-gate'],
  },
  {
    id: 'paradise-mouth',
    type: 'faction',
    title: '天堂口',
    subtitle: '把生存组织化的共同体实验',
    summary: '它是主线里最重要的组织型答案之一，说明终焉里活下去不一定靠天赋，也可以靠管理与秩序。',
    sections: [
      { label: '构成', value: '围绕楚天秋、文巧云、云瑶、张山等人物逐步形成。' },
      { label: '特点', value: '保护、利用、家人话术与服从逻辑同时存在。' },
      { label: '探索价值', value: '它是人物关系从个体协作升级为阵营博弈的桥梁。' },
    ],
    tags: ['天堂口', '组织', '家人话术'],
    timeline: ['paradise-mouth', 'dragon-collapse'],
  },
  {
    id: 'jidao-faction',
    type: 'faction',
    title: '极道',
    subtitle: '以信念拧紧的反抗组织',
    summary: '极道让反抗从零散冲动变成可以被组织、被继承、被动员的长期行动。',
    sections: [
      { label: '构成', value: '以燕知春、江若雪、周末等人为主要骨架。' },
      { label: '特点', value: '更依赖共同信念而非天然默契，因此强度高、波动也高。' },
      { label: '探索价值', value: '适合承载“团体关系如何生长与崩裂”这一专题。' },
    ],
    tags: ['极道', '信念', '组织行动'],
    timeline: ['paradise-mouth', 'dragon-collapse'],
  },
  {
    id: 'cat-team',
    type: 'faction',
    title: '猫队',
    subtitle: '任务联盟式猎杀组织',
    summary: '猫队不像共同体，更像目标明确、完成即散的任务联盟，因此效率极高但情感底盘很薄。',
    sections: [
      { label: '构成', value: '以高压任务、神兽猎杀和临时共谋为主要运行逻辑。' },
      { label: '特点', value: '情感黏性低、目标性强，与主角团和天堂口气质都不同。' },
      { label: '探索价值', value: '适合做关系馆里“任务联盟”类型的主例。' },
    ],
    tags: ['猫队', '任务联盟', '猎杀'],
    timeline: ['dragon-collapse'],
  },
  {
    id: 'dragon-order',
    type: 'faction',
    title: '双龙秩序',
    subtitle: '顶层治理与双核僵局',
    summary: '青龙与天龙并非简单上下级，而是共同维持终焉又彼此牵制的双核政治。',
    sections: [
      { label: '构成', value: '围绕天龙、青龙、天级与神兽建立起来的顶层秩序。' },
      { label: '特点', value: '稳定、残酷、僵死，且连统治者自己都难以挣脱。' },
      { label: '探索价值', value: '它是理解真相层与终局战争的基础外壳。' },
    ],
    tags: ['双龙', '顶层秩序', '神兽'],
    timeline: ['dragon-collapse', 'final-gate'],
  },
];

export const archiveEdges: ArchiveEdge[] = [
  { source: 'qixia', target: 'linqin', label: '共谋' },
  { source: 'qixia', target: 'qiaojiajin', label: '互补' },
  { source: 'qixia', target: 'chenjunnan', label: '默契' },
  { source: 'qixia', target: 'tiantian', label: '保护' },
  { source: 'qixia', target: 'hanyimo', label: '压制' },
  { source: 'qixia', target: 'yunianan', label: '执念' },
  { source: 'qixia', target: 'baiyang', label: '变量对照' },
  { source: 'qixia', target: 'qinglong', label: '认知拉扯' },
  { source: 'qixia', target: 'tianlong', label: '终局对峙' },
  { source: 'linqin', target: 'jidao-faction', label: '短暂咬合' },
  { source: 'chutianqiu', target: 'wenqiaoyun', label: '共创' },
  { source: 'chutianqiu', target: 'yunyao', label: '失衡搭档' },
  { source: 'chutianqiu', target: 'zhangshan', label: '支柱' },
  { source: 'chutianqiu', target: 'jinyuanxun', label: '信息链' },
  { source: 'yanzhichun', target: 'jiangruoxue', label: '王与军师' },
  { source: 'yanzhichun', target: 'jidao-faction', label: '旗帜' },
  { source: 'jiangruoxue', target: 'jidao-faction', label: '连接器' },
  { source: 'zhoumo', target: 'jidao-faction', label: '传音' },
  { source: 'yanzhichun', target: 'luxiaoxiao', label: '执行端' },
  { source: 'yanzhichun', target: 'tongchan', label: '信仰绑定' },
  { source: 'yanzhichun', target: 'guyu', label: '边缘锋刃' },
  { source: 'yanzhichun', target: 'shuhua', label: '白羊路径' },
  { source: 'qixia', target: 'chutianqiu', label: '高位对照' },
  { source: 'chenjunnan', target: 'cat-team', label: '临时共谋' },
  { source: 'qiaojiajin', target: 'dragon-collapse-event', label: '硬撼' },
  { source: 'qixia', target: 'first-room', label: '破局' },
  { source: 'qixia', target: 'echo-awakening-event', label: '觉醒' },
  { source: 'qixia', target: 'endland', label: '逼近' },
  { source: 'qixia', target: 'rules', label: '拆解' },
  { source: 'qixia', target: 'new-world', label: '重写' },
  { source: 'linqin', target: 'first-room', label: '介入' },
  { source: 'linqin', target: 'survival-alliance', label: '塑形' },
  { source: 'qiaojiajin', target: 'survival-alliance', label: '托底' },
  { source: 'chenjunnan', target: 'survival-alliance', label: '串联' },
  { source: 'tiantian', target: 'survival-alliance', label: '施压' },
  { source: 'hanyimo', target: 'first-room', label: '触发' },
  { source: 'lishangling', target: 'survival-alliance', label: '试探' },
  { source: 'lishangling', target: 'first-room', label: '起点' },
  { source: 'sushan', target: 'survival-alliance', label: '协作' },
  { source: 'sushan', target: 'paradise-mouth', label: '咬合' },
  { source: 'qindingdong', target: 'survival-alliance', label: '轻社交' },
  { source: 'qindingdong', target: 'false-alliance-event', label: '边缘站位' },
  { source: 'qianwu', target: 'cat-team', label: '任务位' },
  { source: 'qianduoduo', target: 'cat-team', label: '补位' },
  { source: 'first-room', target: 'human-pig', label: '扩散' },
  { source: 'first-room', target: 'false-alliance-event', label: '引出' },
  { source: 'first-room', target: 'survival-alliance', label: '催生' },
  { source: 'false-alliance-event', target: 'survival-alliance', label: '重排' },
  { source: 'human-snake-quiz', target: 'echo-awakening-event', label: '放大' },
  { source: 'echo-awakening-event', target: 'echo', label: '显影' },
  { source: 'echo-awakening-event', target: 'cycle', label: '撕开' },
  { source: 'paradise-mouth-event', target: 'paradise-mouth', label: '组织化' },
  { source: 'jidao-rise', target: 'jidao-faction', label: '动员' },
  { source: 'dragon-collapse-event', target: 'dragon-order', label: '崩裂' },
  { source: 'dragon-collapse-event', target: 'cat-team', label: '猎杀联动' },
  { source: 'final-train', target: 'dream-reality', label: '重解释' },
  { source: 'final-train', target: 'new-world', label: '汇流' },
  { source: 'endland', target: 'first-room', label: '包裹' },
  { source: 'endland', target: 'rules', label: '承载' },
  { source: 'endland', target: 'taoyuan', label: '前身' },
  { source: 'rules', target: 'first-room', label: '支配' },
  { source: 'rules', target: 'false-alliance-event', label: '挤压' },
  { source: 'cycle', target: 'endland', label: '维稳' },
  { source: 'tiers', target: 'dragon-order', label: '分层' },
  { source: 'dao', target: 'survival-alliance', label: '诱饵' },
  { source: 'empty-house-awakening', target: 'qixia', label: '被卷入' },
  { source: 'empty-house-awakening', target: 'linqin', label: '识别' },
  { source: 'empty-house-awakening', target: 'rules', label: '定调' },
  { source: 'empty-house-awakening', target: 'cycle', label: '提示' },
  { source: 'empty-house-awakening', target: 'endland', label: '框定' },
  { source: 'lie-screening', target: 'qixia', label: '逼迫站位' },
  { source: 'lie-screening', target: 'linqin', label: '试探' },
  { source: 'lie-screening', target: 'rules', label: '暴露' },
  { source: 'lie-screening', target: 'dao', label: '诱导' },
  { source: 'order-clash', target: 'hanyimo', label: '秩序冲突' },
  { source: 'order-clash', target: 'qixia', label: '旁观' },
  { source: 'order-clash', target: 'rules', label: '碾压' },
  { source: 'first-death-loop', target: 'qixia', label: '确认' },
  { source: 'first-death-loop', target: 'cycle', label: '揭示' },
  { source: 'renyang-game', target: 'renyang', label: '淘汰' },
  { source: 'renyang-game', target: 'qixia', label: '博弈' },
  { source: 'renyang-game', target: 'tiers', label: '示范' },
  { source: 'probability-training', target: 'renzhu', label: '样本' },
  { source: 'probability-training', target: 'renyang', label: '训练' },
  { source: 'probability-training', target: 'rules', label: '压迫' },
  { source: 'mouse-game', target: 'qixia', label: '试探' },
  { source: 'monkey-game', target: 'chenjunnan', label: '应变' },
  { source: 'yunyao-echo', target: 'yunyao', label: '回响' },
  { source: 'family-expansion', target: 'chutianqiu', label: '组织' },
  { source: 'jidao-appearance', target: 'yanzhichun', label: '现身' },
  { source: 'zodiac-bet-contract', target: 'baiyang', label: '对赌' },
  { source: 'middle-station', target: 'qixia', label: '过渡' },
  { source: 'dissociation', target: 'tianlong', label: '离析' },
  { source: 'shengshengbuxi', target: 'qixia', label: '回收' },
  { source: 'human-pig', target: 'renzhu', label: '赌局核心' },
  { source: 'human-pig', target: 'qixia', label: '判断' },
  { source: 'human-pig', target: 'rules', label: '施压' },
  { source: 'temporary-coop-event', target: 'qixia', label: '牵头' },
  { source: 'temporary-coop-event', target: 'linqin', label: '加码' },
  { source: 'temporary-coop-event', target: 'qiaojiajin', label: '执行' },
  { source: 'temporary-coop-event', target: 'survival-alliance', label: '雏形' },
  { source: 'false-alliance-event', target: 'qixia', label: '试探' },
  { source: 'false-alliance-event', target: 'linqin', label: '计算' },
  { source: 'moral-shift', target: 'qixia', label: '转向' },
  { source: 'moral-shift', target: 'tiantian', label: '牵引' },
  { source: 'moral-shift', target: 'rules', label: '改写' },
  { source: 'core-ensemble', target: 'qixia', label: '认知核心' },
  { source: 'core-ensemble', target: 'linqin', label: '共谋' },
  { source: 'core-ensemble', target: 'qiaojiajin', label: '执行' },
  { source: 'core-ensemble', target: 'chenjunnan', label: '串联' },
  { source: 'core-ensemble', target: 'survival-alliance', label: '定型' },
  { source: 'trust-reorder-event', target: 'qixia', label: '重排' },
  { source: 'trust-reorder-event', target: 'chenjunnan', label: '串联' },
  { source: 'trust-reorder-event', target: 'survival-alliance', label: '震荡' },
  { source: 'information-gap', target: 'qixia', label: '掌控' },
  { source: 'information-gap', target: 'linqin', label: '补刀' },
  { source: 'information-gap', target: 'dao', label: '诱饵' },
  { source: 'earth-snake', target: 'dishe', label: '主持' },
  { source: 'earth-snake', target: 'qixia', label: '破局' },
  { source: 'earth-snake', target: 'rules', label: '加压' },
  { source: 'diji-game', target: 'qixia', label: '破局' },
  { source: 'diji-game', target: 'chenjunnan', label: '保全' },
  { source: 'diji-game', target: 'rules', label: '压迫' },
  { source: 'human-snake-quiz', target: 'renshe', label: '出题' },
  { source: 'human-snake-quiz', target: 'qixia', label: '解题' },
  { source: 'human-snake-quiz', target: 'rules', label: '挤压' },
  { source: 'high-pressure-quiz', target: 'dishe', label: '压制' },
  { source: 'high-pressure-quiz', target: 'renshe', label: '施压' },
  { source: 'high-pressure-quiz', target: 'rules', label: '放大' },
  { source: 'echo-awakening-event', target: 'qixia', label: '觉醒' },
  { source: 'echo-awakening-event', target: 'linqin', label: '跟进' },
  { source: 'echo-awakening-event', target: 'qiaojiajin', label: '守住' },
  { source: 'zodiac-system', target: 'tiers', label: '层级化' },
  { source: 'zodiac-system', target: 'baiyang', label: '主导' },
  { source: 'zodiac-system', target: 'qinglong', label: '监管' },
  { source: 'paradise-mouth-event', target: 'chutianqiu', label: '建制' },
  { source: 'paradise-mouth-event', target: 'wenqiaoyun', label: '调度' },
  { source: 'paradise-mouth-event', target: 'yunyao', label: '协作' },
  { source: 'paradise-mouth-event', target: 'zhangshan', label: '支撑' },
  { source: 'liangren-king', target: 'chutianqiu', label: '名望' },
  { source: 'liangren-king', target: 'wenqiaoyun', label: '治理' },
  { source: 'liangren-king', target: 'yunyao', label: '见证' },
  { source: 'liangren-king', target: 'paradise-mouth', label: '合法性' },
  { source: 'faction-formation', target: 'chutianqiu', label: '组织' },
  { source: 'faction-formation', target: 'yanzhichun', label: '反抗' },
  { source: 'faction-formation', target: 'paradise-mouth', label: '集结' },
  { source: 'faction-formation', target: 'jidao-faction', label: '结盟' },
  { source: 'jidao-rise', target: 'yanzhichun', label: '号召' },
  { source: 'jidao-rise', target: 'jiangruoxue', label: '谋划' },
  { source: 'rebellion-day', target: 'qiaojiajin', label: '救人' },
  { source: 'rebellion-day', target: 'yanzhichun', label: '响应' },
  { source: 'rebellion-day', target: 'jidao-faction', label: '行动化' },
  { source: 'bliss-bank', target: 'baiyang', label: '收益模型' },
  { source: 'bliss-bank', target: 'jinyuanxun', label: '资源' },
  { source: 'bliss-bank', target: 'dao', label: '牵引' },
  { source: 'white-sheep-ascent', target: 'baiyang', label: '晋升' },
  { source: 'white-sheep-ascent', target: 'tianlong', label: '背书' },
  { source: 'white-sheep-ascent', target: 'dragon-order', label: '靠近' },
  { source: 'tianma-principle', target: 'chutianqiu', label: '碰触' },
  { source: 'tianma-principle', target: 'hanyimo', label: '见证' },
  { source: 'tianma-principle', target: 'dragon-order', label: '显影' },
  { source: 'beast-oppression', target: 'qinglong', label: '压迫' },
  { source: 'beast-oppression', target: 'tianlong', label: '清场' },
  { source: 'beast-oppression', target: 'dragon-order', label: '统治' },
  { source: 'dragon-collapse-event', target: 'qinglong', label: '震荡' },
  { source: 'dragon-collapse-event', target: 'tianlong', label: '裂缝' },
  { source: 'dragon-collapse-event', target: 'chutianqiu', label: '对照' },
  { source: 'dragon-collapse-event', target: 'zhangshan', label: '硬顶' },
  { source: 'zodiac-confrontation', target: 'qixia', label: '反攻' },
  { source: 'zodiac-confrontation', target: 'qiaojiajin', label: '硬撼' },
  { source: 'zodiac-confrontation', target: 'dragon-order', label: '冲撞' },
  { source: 'qinglong-downfall', target: 'qinglong', label: '失势' },
  { source: 'qinglong-downfall', target: 'qiaojiajin', label: '击败' },
  { source: 'qinglong-downfall', target: 'zhangshan', label: '配合' },
  { source: 'qinglong-downfall', target: 'dragon-order', label: '松动' },
  { source: 'mandela-effect', target: 'yanzhichun', label: '错位' },
  { source: 'mandela-effect', target: 'jiangruoxue', label: '偏差' },
  { source: 'mandela-effect', target: 'dream-reality', label: '漂移' },
  { source: 'truth-approach-event', target: 'qixia', label: '追问' },
  { source: 'truth-approach-event', target: 'xuliunian', label: '指引' },
  { source: 'truth-approach-event', target: 'endland', label: '逼近' },
  { source: 'tianlong-dissociation', target: 'tianlong', label: '离析' },
  { source: 'tianlong-dissociation', target: 'qixia', label: '对峙' },
  { source: 'tianlong-dissociation', target: 'dream-reality', label: '撕开' },
  { source: 'final-train', target: 'qixia', label: '登车' },
  { source: 'final-train', target: 'yunianan', label: '牵引' },
  { source: 'giant-clock-event', target: 'qixia', label: '进入' },
  { source: 'giant-clock-event', target: 'xuliunian', label: '线索' },
  { source: 'giant-clock-event', target: 'dream-reality', label: '揭示' },
  { source: 'how-win', target: 'qixia', label: '重写' },
  { source: 'how-win', target: 'linqin', label: '共识' },
  { source: 'win-method', target: 'qixia', label: '策略' },
  { source: 'win-method', target: 'qiaojiajin', label: '执行' },
  { source: 'endgame-rewrite', target: 'qixia', label: '改写' },
  { source: 'endgame-rewrite', target: 'new-world', label: '重构' },
  { source: 'immortality-paradox', target: 'qixia', label: '质疑' },
  { source: 'immortality-paradox', target: 'yunianan', label: '心结' },
  { source: 'immortality-paradox', target: 'cycle', label: '悖论' },
  { source: 'endgame-ethos', target: 'qixia', label: '选择' },
  { source: 'endgame-ethos', target: 'linqin', label: '共识' },
  { source: 'endgame-ethos', target: 'new-world', label: '回收' },
  { source: 'reset-resonance', target: 'xuliunian', label: '余震' },
  { source: 'reset-resonance', target: 'dream-reality', label: '未回收' },
  { source: 'qixia-variable', target: 'qixia', label: '变量' },
  { source: 'qixia-variable', target: 'tianlong', label: '对照' },
  { source: 'qixia-variable', target: 'new-world', label: '解释' },
  { source: 'prehistory-layout', target: 'xuliunian', label: '布局' },
  { source: 'prehistory-layout', target: 'yunianan', label: '起点' },
  { source: 'prehistory-layout', target: 'taoyuan', label: '前史' },
];

export const timelineEvents: TimelineEvent[] = [
  {
    id: 'prelude-memory',
    label: '旧世界裂口',
    phase: 'BEFORE DAY 01',
    detail: '余念安、许流年与现实感一起构成了终焉之前最后的锚点，人物还以为自己仍在旧秩序里。'
  },
  {
    id: 'opening-bet',
    label: '空屋与开局',
    phase: 'DAY 01',
    detail: '第一间房与说谎筛人把陌生人推入同一局面，信任第一次被改写成了生存手段。',
  },
  {
    id: 'false-alliance',
    label: '人鼠 / 人猪赌命期',
    phase: 'DAY 02',
    detail: '鼠类游戏、人猪赌命与早期概率型训练把恐惧、侥幸和站位一起推上台面。',
  },
  {
    id: 'echo-awakening',
    label: '临时同盟与伪同盟',
    phase: 'MID LOOP',
    detail: '临时合作先于信任出现，人物在多轮震荡中形成伪同盟与更稳定的共犯网络。',
  },
  {
    id: 'paradise-mouth',
    label: '回响与人蛇问答',
    phase: 'LATE LOOP',
    detail: '回响显影、语义博弈与人蛇问答让能力、记忆和规则理解一起升级。',
  },
  {
    id: 'dragon-collapse',
    label: '天堂口与极道成形',
    phase: 'ENDGAME',
    detail: '天堂口的组织化生存与极道的反抗组织开始成形，阵营博弈跃迁为结构战争。',
  },
  {
    id: 'white-sheep-path',
    label: '白羊之路与对赌',
    phase: 'DAY 11',
    detail: '白羊晋升、对赌合同与高位规则把层级跃迁制度化，胜负开始绑定命运。'
  },
  {
    id: 'dragon-fracture',
    label: '双龙失稳与神兽压迫',
    phase: 'ENDGAME',
    detail: '青龙、天龙与神兽体系的压迫逐渐失稳，终焉从关卡叙事跃迁为秩序崩塌。'
  },
  {
    id: 'final-gate-approach',
    label: '列车与第二站',
    phase: 'DAY 11+',
    detail: '列车、第二站与中间站把所有人物、事件与真相拖向终局重解释。'
  },
  {
    id: 'final-gate',
    label: '终局重写与生生不息',
    phase: 'DAY 11+',
    detail: '胜利条件被重写，复活悖论被收束，整部作品的最终解释回到生生不息。'
  },
];

export const flowCards: FlowCard[] = [
  {
    id: 'strangers',
    title: '陌生人入局',
    subtitle: '所有链路的原始状态',
    summary: '人物还没有真正关系，只有恐惧、猜疑和被迫进入同一空间的初始失衡。',
    type: 'transition',
  },
  {
    id: 'qixia-flow',
    title: '齐夏',
    subtitle: '观察开始替代慌乱',
    summary: '他先把局面看成规则问题，再逐步把规则变成自己可用的工具。',
    type: 'character',
  },
  {
    id: 'linqin-flow',
    title: '林檎',
    subtitle: '先识别，再加码',
    summary: '她不是被带着走，而是迅速识别齐夏的价值，并把合作推向更锋利的共谋。',
    type: 'character',
  },
  {
    id: 'qiaojiajin-flow',
    title: '乔家劲',
    subtitle: '行动价值开始成形',
    summary: '他把抽象判断向执行层落下去，保证团队不只会想。',
    type: 'character',
  },
  {
    id: 'chenjunnan-flow',
    title: '陈俊南',
    subtitle: '把松散的人重新连住',
    summary: '他让人物之间不只是规则上的合作，还带上复杂的人情和游离感。',
    type: 'character',
  },
  {
    id: 'first-room-flow',
    title: '第一间房试炼',
    subtitle: '第一次关系洗牌',
    summary: '这不是开场说明，而是全书人物关系第一次被强行改写的总起点。',
    type: 'event',
  },
  {
    id: 'trial-bargain',
    title: '临时合作出现',
    subtitle: '先一起活，再谈信任',
    summary: '合作并不是信任的结果，而是规则压力下不得不发生的短期站位。',
    type: 'event',
  },
  {
    id: 'group-formation',
    title: '主角团雏形生成',
    subtitle: '从散点变成结构',
    summary: '齐夏、林檎、乔家劲、陈俊南之间逐渐形成认知、共谋、执行、串联的初步分工。',
    type: 'event',
  },
  {
    id: 'reorder-event',
    title: '关系震荡与重排',
    subtitle: '谁能留下，谁会被甩开',
    summary: '事件开始不断改写人物位置，合作与背叛一并存在，队伍结构被反复震荡。',
    type: 'event',
  },
  {
    id: 'truth-approach',
    title: '真相逼近',
    subtitle: '求生线开始转向认知线',
    summary: '一些人物不再只是在活下去，而开始主动逼近终焉之地背后的结构。',
    type: 'event',
  },
  {
    id: 'survival-pressure',
    title: '生存压力',
    subtitle: '道德判断被迫退位',
    summary: '规则把所有人的第一反应从“对不对”改成“能不能活”。',
    type: 'mechanic',
  },
  {
    id: 'info-gap',
    title: '信息差',
    subtitle: '谁解释规则，谁就有权力',
    summary: '信息不完整让试探、误导和判断权成为人物关系的核心变量。',
    type: 'mechanic',
  },
  {
    id: 'game-rules-flow',
    title: '游戏规则',
    subtitle: '不是背景，而是推动器',
    summary: '规则不断重排人物关系和事件走向，它本身就是主线里的隐形施力者。',
    type: 'mechanic',
  },
  {
    id: 'moral-friction',
    title: '道德摩擦',
    subtitle: '策略开始带痛感',
    summary: '甜甜这类角色把代价具体化，让团队选择永远无法只停留在策略层。',
    type: 'mechanic',
  },
  {
    id: 'trust-distortion',
    title: '信任异化',
    subtitle: '关系开始变脏',
    summary: '人物不是慢慢变熟，而是在压力里把信任先变成了工具。',
    type: 'result',
  },
  {
    id: 'co-conspirator-net',
    title: '共犯结构',
    subtitle: '合作、怀疑、保护并存',
    summary: '主角团不是传统意义上的同伴，而是一组在极端环境里被迫互相拖拽的节点。',
    type: 'result',
  },
  {
    id: 'high-pressure-team',
    title: '高压协作网络',
    subtitle: '从同路到彼此嵌合',
    summary: '认知、共谋、行动和串联变成可持续结构，关系开始具备长期作用。',
    type: 'result',
  },
  {
    id: 'truth-line',
    title: '终焉之地',
    subtitle: '真相层开始浮出',
    summary: '它不再只是背景名词，而开始反向解释前面的事件和人物关系。',
    type: 'result',
  },
  {
    id: 'phase-next',
    title: '进入下一次终焉',
    subtitle: '结构开始震荡',
    summary: '当前阶段形成的关系将在下一段被反复验证、拉扯和重写。',
    type: 'transition',
  },
];

export const doomPhases: DoomPhase[] = [
  {
    id: 'phase-1',
    rangeLabel: '第1次终焉',
    title: '关系被强行启动',
    kicker: '陌生人被投入同一空间，规则第一次代替日常秩序，所有人物从散点变成一张网的起点。',
    keywords: ['第一间房', '齐夏', '试探', '共犯结构'],
    entry: '从第一间房开始，规则先逼所有人站位，关系才有机会生成。',
    lanes: [
      { id: 'premise', title: '前因区', cardIds: ['strangers', 'qixia-flow', 'linqin-flow'] },
      { id: 'mechanics', title: '机制区', cardIds: ['survival-pressure', 'info-gap', 'game-rules-flow'] },
      { id: 'events', title: '事件区', cardIds: ['first-room-flow', 'trial-bargain'] },
      { id: 'outcomes', title: '结果区', cardIds: ['trust-distortion', 'co-conspirator-net'] },
      { id: 'next', title: '下一跳区', cardIds: ['phase-next'] },
    ],
  },
  {
    id: 'phase-2',
    rangeLabel: '第2-3次终焉',
    title: '试探开始变成临时合作',
    kicker: '齐夏开始成为判断中心，林檎完成识别，人物关系第一次出现可持续的短期分工。',
    keywords: ['林檎', '临时合作', '信息差', '齐夏'],
    entry: '这里不是队伍成立，而是彼此开始接受“暂时一起走”这件事。',
    lanes: [
      { id: 'premise', title: '前因区', cardIds: ['qixia-flow', 'linqin-flow', 'qiaojiajin-flow'] },
      { id: 'mechanics', title: '机制区', cardIds: ['info-gap', 'game-rules-flow', 'moral-friction'] },
      { id: 'events', title: '事件区', cardIds: ['trial-bargain', 'group-formation'] },
      { id: 'outcomes', title: '结果区', cardIds: ['co-conspirator-net', 'high-pressure-team'] },
      { id: 'next', title: '下一跳区', cardIds: ['phase-next'] },
    ],
  },
  {
    id: 'phase-3',
    rangeLabel: '第4-6次终焉',
    title: '主角团雏形生成',
    kicker: '认知、共谋、执行、串联开始稳定出现，队伍结构第一次从临时合作升级为能持续运转的高压网络。',
    keywords: ['乔家劲', '陈俊南', '主角团', '高压协作'],
    entry: '这一段真正重要的不是“谁加入了队伍”，而是每个人开始承担什么功能。',
    lanes: [
      { id: 'premise', title: '前因区', cardIds: ['qixia-flow', 'linqin-flow', 'qiaojiajin-flow', 'chenjunnan-flow'] },
      { id: 'mechanics', title: '机制区', cardIds: ['game-rules-flow', 'info-gap', 'moral-friction'] },
      { id: 'events', title: '事件区', cardIds: ['group-formation'] },
      { id: 'outcomes', title: '结果区', cardIds: ['high-pressure-team', 'co-conspirator-net'] },
      { id: 'next', title: '下一跳区', cardIds: ['reorder-event'] },
    ],
  },
  {
    id: 'phase-4',
    rangeLabel: '第7-10次终焉',
    title: '关系震荡与反复重排',
    kicker: '原本形成的合作结构被持续验证和撕扯，人物位置不断被事件重新定义。',
    keywords: ['重排', '背叛', '站位', '震荡'],
    entry: '这一段会让“谁能走下去”这件事持续失去确定性。',
    lanes: [
      { id: 'premise', title: '前因区', cardIds: ['chenjunnan-flow', 'qiaojiajin-flow', 'group-formation'] },
      { id: 'mechanics', title: '机制区', cardIds: ['survival-pressure', 'info-gap', 'game-rules-flow'] },
      { id: 'events', title: '事件区', cardIds: ['reorder-event'] },
      { id: 'outcomes', title: '结果区', cardIds: ['trust-distortion', 'high-pressure-team'] },
      { id: 'next', title: '下一跳区', cardIds: ['truth-approach'] },
    ],
  },
  {
    id: 'phase-5',
    rangeLabel: '第11次终焉以后',
    title: '人物线与真相线开始汇流',
    kicker: '求生不再是唯一目的，人物开始主动摸向终焉之地与规则背后的更深结构。',
    keywords: ['终焉之地', '真相', '规则', '回收'],
    entry: '前面的关系与事件开始被真相层反向照亮，整张网慢慢闭合。',
    lanes: [
      { id: 'premise', title: '前因区', cardIds: ['qixia-flow', 'linqin-flow', 'reorder-event'] },
      { id: 'mechanics', title: '机制区', cardIds: ['game-rules-flow', 'info-gap'] },
      { id: 'events', title: '事件区', cardIds: ['truth-approach'] },
      { id: 'outcomes', title: '结果区', cardIds: ['truth-line', 'high-pressure-team'] },
      { id: 'next', title: '下一跳区', cardIds: ['truth-line'] },
    ],
  },
];

export const riverStages: RiverStage[] = [
  {
    id: 'prelude',
    rangeLabel: '终焉之前',
    title: '日常秩序尚未崩裂',
    kicker: '人物还在旧世界的惯性里，关系尚未被规则污染，这一段先作为整条长河的源头占位。',
    keywords: ['旧秩序', '人物初始状态', '世界背景'],
    coreCharacters: ['齐夏', '余念安', '许流年'],
    coreEvents: ['旧秩序尚未崩塌', '最初的缺口'],
    coreMechanics: ['记忆缺失', '旧世界惯性'],
    stageResult: '人物被推向终焉的入口，旧秩序的稳定性开始失效。',
  },
  {
    id: 'phase-1',
    rangeLabel: '第1次终焉',
    title: '关系被强行启动',
    kicker: '第一间房让所有人第一次被规则拖进同一张网里。',
    keywords: ['第一间房', '试探', '共犯结构'],
    coreCharacters: ['齐夏', '林檎', '乔家劲', '陈俊南'],
    coreEvents: ['第一间房试炼', '临时合作出现'],
    coreMechanics: ['生存压力', '信息差', '游戏规则'],
    stageResult: '信任开始异化，陌生人第一次被迫变成同一张关系网里的节点。',
  },
  {
    id: 'phase-2',
    rangeLabel: '第2-3次终焉',
    title: '试探开始变成临时合作',
    kicker: '伪同盟、人猪与人蛇等局面不断迫使人物从试探转向条件式协作。',
    keywords: ['伪同盟', '人猪', '人蛇', '信息差'],
    coreCharacters: ['齐夏', '林檎', '乔家劲', '韩一墨'],
    coreEvents: ['伪同盟成形', '人猪游戏', '人蛇·问答游戏'],
    coreMechanics: ['信息差', '道德摩擦', '规则挤压'],
    stageResult: '短期协作形成，但所有合作都带着随时会崩开的灰色边界。',
  },
  {
    id: 'phase-3',
    rangeLabel: '第4-6次终焉',
    title: '主角团雏形生成',
    kicker: '认知、共谋、执行与串联开始形成更稳定的分工，回响也逐步把人物推向更深层的博弈。',
    keywords: ['回响', '主角团', '互补分工'],
    coreCharacters: ['齐夏', '林檎', '乔家劲', '陈俊南', '甜甜'],
    coreEvents: ['回响觉醒', '主角团雏形生成', '分工稳定化'],
    coreMechanics: ['回响', '互补分工', '高压协作'],
    stageResult: '主角团从短暂抱团，升级成可持续运转的高压协作网络。',
  },
  {
    id: 'phase-4',
    rangeLabel: '第7-10次终焉',
    title: '关系震荡与反复重排',
    kicker: '天堂口、极道与双龙秩序把个体关系升级为阵营、结构和神兽层面的重排。',
    keywords: ['天堂口', '极道', '双龙', '重排'],
    coreCharacters: ['楚天秋', '燕知春', '文巧云', '云瑶', '张山'],
    coreEvents: ['天堂口事件', '极道崛起', '双龙秩序失稳'],
    coreMechanics: ['组织化生存', '重新结盟', '结构重排'],
    stageResult: '人物位置和阵营边界被反复改写，真正的核心与边缘开始分层。',
  },
  {
    id: 'phase-5',
    rangeLabel: '第11次终焉以后',
    title: '人物线与真相线开始汇流',
    kicker: '列车、第二站、梦与现实、新世界这些终局节点，开始反向解释前面所有阶段。',
    keywords: ['第二站', '新世界', '终焉之地', '认知升级'],
    coreCharacters: ['齐夏', '许流年', '余念安', '楚天秋'],
    coreEvents: ['列车与第二站', '真相逼近', '新世界重写'],
    coreMechanics: ['回响', '规则回收', '认知升级', '终局重写'],
    stageResult: '人物、事件和世界观开始汇流，前文被拖入更大的解释框架。',
  },
  {
    id: 'finale',
    rangeLabel: '终局',
    title: '终局回收',
    kicker: '所有关系、事件和规则都被拖回同一个解释框架，长河在这里闭合，但解释仍保留余震。',
    keywords: ['终局', '回收', '新世界', '余震'],
    coreCharacters: ['齐夏', '余念安', '楚天秋', '燕知春'],
    coreEvents: ['终局回收', '结构坍塌', '列车与第二站', '新世界重写'],
    coreMechanics: ['终局重置', '结构闭环', '重解释'],
    stageResult: '终焉的链条在这里回收，人物关系、规则和真相获得最终解释。',
  },
];

export const museumHalls: MuseumHall[] = [
  {
    id: 'characters',
    title: '人物馆',
    label: 'Archive: Personae',
    subtitle: '人物定位 · 心理变化 · 关键关系',
    description: '从人物定位、关键事件、心理变化和人物细节出发，重新理解每一个人的命运轨迹。',
    accent: 'primary',
  },
  {
    id: 'events',
    title: '事件馆',
    label: 'Chronicle: Events',
    subtitle: '规则剖面 · 过程拆解 · 结果回流',
    description: '把关键房间、关键局和主线事件拆开陈列，查看事件如何改写人物和结构。',
    accent: 'secondary',
  },
  {
    id: 'world',
    title: '世界观馆',
    label: 'Atlas: Cosmology',
    subtitle: '规则层 · 结构层 · 真相层',
    description: '从回响、终焉之地、轮回结构到终局回收，建立更宏大的解释框架。',
    accent: 'primary',
  },
  {
    id: 'relations',
    title: '关系馆',
    label: 'Nexus: Bonds',
    subtitle: '共谋 · 试探 · 保护 · 背叛',
    description: '按关系类型进入《十日终焉》，查看人与人之间最复杂也最危险的连接方式。',
    accent: 'muted',
  },
];

export const riverNodes: RiverNode[] = [
  { id: 'prelude-order', cardId: 'strangers', stageId: 'prelude', band: 'prelude', x: 8, y: 52, size: 'md', importance: 1 },
  { id: 'prelude-world', cardId: 'truth-line', stageId: 'prelude', band: 'transition', x: 14, y: 76, size: 'sm', importance: 1 },

  { id: 'phase1-pressure', cardId: 'survival-pressure', stageId: 'phase-1', band: 'mechanic', x: 22, y: 18, size: 'sm', importance: 1 },
  { id: 'phase1-info', cardId: 'info-gap', stageId: 'phase-1', band: 'mechanic', x: 28, y: 24, size: 'sm', importance: 2 },
  { id: 'phase1-qixia', cardId: 'qixia-flow', stageId: 'phase-1', band: 'core', x: 24, y: 48, size: 'md', importance: 2 },
  { id: 'phase1-linqin', cardId: 'linqin-flow', stageId: 'phase-1', band: 'core', x: 20, y: 68, size: 'sm', importance: 1 },
  { id: 'phase1-firstroom', cardId: 'first-room-flow', stageId: 'phase-1', band: 'core', x: 30, y: 52, size: 'lg', importance: 3 },
  { id: 'phase1-trial', cardId: 'trial-bargain', stageId: 'phase-1', band: 'core', x: 36, y: 44, size: 'md', importance: 2 },
  { id: 'phase1-trust', cardId: 'trust-distortion', stageId: 'phase-1', band: 'outcome', x: 37, y: 70, size: 'sm', importance: 1 },
  { id: 'phase1-net', cardId: 'co-conspirator-net', stageId: 'phase-1', band: 'outcome', x: 41, y: 58, size: 'md', importance: 2 },

  { id: 'phase2-rules', cardId: 'game-rules-flow', stageId: 'phase-2', band: 'mechanic', x: 46, y: 18, size: 'sm', importance: 1 },
  { id: 'phase2-linqin', cardId: 'linqin-flow', stageId: 'phase-2', band: 'core', x: 48, y: 38, size: 'sm', importance: 1 },
  { id: 'phase2-qixia', cardId: 'qixia-flow', stageId: 'phase-2', band: 'core', x: 52, y: 48, size: 'md', importance: 2 },
  { id: 'phase2-qiaojiajin', cardId: 'qiaojiajin-flow', stageId: 'phase-2', band: 'core', x: 50, y: 68, size: 'sm', importance: 1 },
  { id: 'phase2-formation', cardId: 'group-formation', stageId: 'phase-2', band: 'core', x: 58, y: 50, size: 'lg', importance: 3 },
  { id: 'phase2-team', cardId: 'high-pressure-team', stageId: 'phase-2', band: 'outcome', x: 61, y: 66, size: 'md', importance: 2 },

  { id: 'phase3-moral', cardId: 'moral-friction', stageId: 'phase-3', band: 'mechanic', x: 64, y: 20, size: 'sm', importance: 1 },
  { id: 'phase3-chenjunnan', cardId: 'chenjunnan-flow', stageId: 'phase-3', band: 'core', x: 68, y: 34, size: 'sm', importance: 1 },
  { id: 'phase3-qiaojiajin', cardId: 'qiaojiajin-flow', stageId: 'phase-3', band: 'core', x: 70, y: 56, size: 'md', importance: 2 },
  { id: 'phase3-team', cardId: 'high-pressure-team', stageId: 'phase-3', band: 'core', x: 75, y: 48, size: 'lg', importance: 3 },
  { id: 'phase3-cocon', cardId: 'co-conspirator-net', stageId: 'phase-3', band: 'outcome', x: 78, y: 72, size: 'md', importance: 2 },

  { id: 'phase4-pressure', cardId: 'survival-pressure', stageId: 'phase-4', band: 'mechanic', x: 82, y: 20, size: 'sm', importance: 1 },
  { id: 'phase4-reorder', cardId: 'reorder-event', stageId: 'phase-4', band: 'core', x: 87, y: 46, size: 'lg', importance: 3 },
  { id: 'phase4-trust', cardId: 'trust-distortion', stageId: 'phase-4', band: 'outcome', x: 91, y: 64, size: 'md', importance: 2 },

  { id: 'phase5-rules', cardId: 'game-rules-flow', stageId: 'phase-5', band: 'mechanic', x: 98, y: 18, size: 'sm', importance: 1 },
  { id: 'phase5-truth-approach', cardId: 'truth-approach', stageId: 'phase-5', band: 'core', x: 104, y: 44, size: 'lg', importance: 3 },
  { id: 'phase5-qixia', cardId: 'qixia-flow', stageId: 'phase-5', band: 'core', x: 100, y: 64, size: 'md', importance: 2 },
  { id: 'phase5-truth', cardId: 'truth-line', stageId: 'phase-5', band: 'outcome', x: 109, y: 62, size: 'lg', importance: 3 },

  { id: 'finale-truth', cardId: 'truth-line', stageId: 'finale', band: 'core', x: 118, y: 44, size: 'md', importance: 2 },
  { id: 'finale-team', cardId: 'high-pressure-team', stageId: 'finale', band: 'outcome', x: 123, y: 58, size: 'sm', importance: 1 },
];

export const riverLinks: RiverLink[] = [
  { source: 'prelude-order', target: 'phase1-firstroom', strength: 'medium' },
  { source: 'prelude-world', target: 'phase1-info', strength: 'soft' },
  { source: 'phase1-pressure', target: 'phase1-firstroom', strength: 'soft' },
  { source: 'phase1-info', target: 'phase1-qixia', strength: 'soft' },
  { source: 'phase1-qixia', target: 'phase1-firstroom', strength: 'strong' },
  { source: 'phase1-linqin', target: 'phase1-firstroom', strength: 'soft' },
  { source: 'phase1-firstroom', target: 'phase1-trial', strength: 'strong' },
  { source: 'phase1-trial', target: 'phase1-trust', strength: 'medium' },
  { source: 'phase1-trial', target: 'phase1-net', strength: 'strong' },
  { source: 'phase1-net', target: 'phase2-qixia', strength: 'medium' },
  { source: 'phase1-trust', target: 'phase2-linqin', strength: 'soft' },

  { source: 'phase2-rules', target: 'phase2-formation', strength: 'soft' },
  { source: 'phase2-linqin', target: 'phase2-formation', strength: 'soft' },
  { source: 'phase2-qixia', target: 'phase2-formation', strength: 'strong' },
  { source: 'phase2-qiaojiajin', target: 'phase2-formation', strength: 'soft' },
  { source: 'phase2-formation', target: 'phase2-team', strength: 'strong' },
  { source: 'phase2-team', target: 'phase3-team', strength: 'medium' },

  { source: 'phase3-moral', target: 'phase3-team', strength: 'soft' },
  { source: 'phase3-chenjunnan', target: 'phase3-team', strength: 'soft' },
  { source: 'phase3-qiaojiajin', target: 'phase3-team', strength: 'medium' },
  { source: 'phase3-team', target: 'phase3-cocon', strength: 'strong' },
  { source: 'phase3-team', target: 'phase4-reorder', strength: 'strong' },

  { source: 'phase4-pressure', target: 'phase4-reorder', strength: 'soft' },
  { source: 'phase4-reorder', target: 'phase4-trust', strength: 'strong' },
  { source: 'phase4-reorder', target: 'phase5-truth-approach', strength: 'medium' },

  { source: 'phase5-rules', target: 'phase5-truth-approach', strength: 'soft' },
  { source: 'phase5-qixia', target: 'phase5-truth-approach', strength: 'medium' },
  { source: 'phase5-truth-approach', target: 'phase5-truth', strength: 'strong' },
  { source: 'phase5-truth', target: 'finale-truth', strength: 'strong' },
  { source: 'phase5-truth', target: 'finale-team', strength: 'soft' },
];